--------------------------------------------------------------------------------
-- <auto-generated>                                                           --
--     This code was generated by a tool.                                     --
--                                                                            --
--     Changes to this file may cause incorrect behavior and will be lost if  --
--     the code is regenerated.                                               --
-- </auto-generated>                                                          --
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--                                                                            --
--    Copyright(c) 2023 Alexander Gamper, All Rights Reserved.                --
--                                                                            --
--    Ada-WinRT                                                               --
--    Version   : 3.0.0.0                                                     --
--                                                                            --
-- This program is free software: you can redistribute it and / or modify     --
-- it under the terms of the GNU Lesser General Public License as published by--
-- the Free Software Foundation, either version 3 of the License, or          --
-- (at your option) any later version.                                        --
--                                                                            --
-- This program is distributed in the hope that it will be useful,            --
-- but WITHOUT ANY WARRANTY; without even the implied warranty of             --
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the               --
-- GNU Lesser General Public License for more details.                        --
--                                                                            --
-- You should have received a copy of the GNU Lesser General Public License   --
-- along with this program.If not, see http://www.gnu.org/licenses            --
--                                                                            --
--------------------------------------------------------------------------------
with WinUI3.Windows.Foundation; use WinUI3.Windows.Foundation;
with Ada.Unchecked_Deallocation;
--------------------------------------------------------------------------------
package body WinUI3.Windows.System.Threading.Core is

   -----------------------------------------------------------------------------
   -- RuntimeClass Initialization/Finalization for PreallocatedWorkItem

   procedure Initialize (this : in out PreallocatedWorkItem) is
   begin
      null;
   end;

   procedure Finalize (this : in out PreallocatedWorkItem) is
      temp : WinUI3.UInt32 := 0;
      procedure Free is new Ada.Unchecked_Deallocation (IPreallocatedWorkItem, IPreallocatedWorkItem_Ptr);
   begin
      if this.m_IPreallocatedWorkItem /= null then
         if this.m_IPreallocatedWorkItem.all /= null then
            temp := this.m_IPreallocatedWorkItem.all.Release;
            Free (this.m_IPreallocatedWorkItem);
         end if;
      end if;
   end;

   -----------------------------------------------------------------------------
   -- RuntimeClass Constructors for PreallocatedWorkItem

   function Constructor
   (
      handler : WinUI3.Windows.System.Threading.WorkItemHandler
   )
   return PreallocatedWorkItem is
      Hr           : WinUI3.HResult := S_OK;
      tmp          : WinUI3.HResult := S_OK;
      m_hString    : constant WinUI3.HString := To_HString ("Windows.System.Threading.Core.IPreallocatedWorkItem");
      m_Factory    : access IPreallocatedWorkItemFactory_Interface'Class := null;
      temp         : WinUI3.UInt32 := 0;
      m_ComRetVal  : aliased WinUI3.Windows.System.Threading.Core.IPreallocatedWorkItem;
   begin
      return RetVal : PreallocatedWorkItem do
         Hr := RoGetActivationFactory (m_hString, IID_IPreallocatedWorkItemFactory'Access , m_Factory'Address);
         if Hr = S_OK then
            Hr := m_Factory.CreateWorkItem (handler, m_ComRetVal'Access);
            Retval.m_IPreallocatedWorkItem := new WinUI3.Windows.System.Threading.Core.IPreallocatedWorkItem;
            Retval.m_IPreallocatedWorkItem.all := m_ComRetVal;
            temp := m_Factory.Release;
         end if;
         tmp := WindowsDeleteString (m_hString);
      end return;
   end;

   function Constructor
   (
      handler : WinUI3.Windows.System.Threading.WorkItemHandler;
      priority : WinUI3.Windows.System.Threading.WorkItemPriority
   )
   return PreallocatedWorkItem is
      Hr           : WinUI3.HResult := S_OK;
      tmp          : WinUI3.HResult := S_OK;
      m_hString    : constant WinUI3.HString := To_HString ("Windows.System.Threading.Core.IPreallocatedWorkItem");
      m_Factory    : access IPreallocatedWorkItemFactory_Interface'Class := null;
      temp         : WinUI3.UInt32 := 0;
      m_ComRetVal  : aliased WinUI3.Windows.System.Threading.Core.IPreallocatedWorkItem;
   begin
      return RetVal : PreallocatedWorkItem do
         Hr := RoGetActivationFactory (m_hString, IID_IPreallocatedWorkItemFactory'Access , m_Factory'Address);
         if Hr = S_OK then
            Hr := m_Factory.CreateWorkItemWithPriority (handler, priority, m_ComRetVal'Access);
            Retval.m_IPreallocatedWorkItem := new WinUI3.Windows.System.Threading.Core.IPreallocatedWorkItem;
            Retval.m_IPreallocatedWorkItem.all := m_ComRetVal;
            temp := m_Factory.Release;
         end if;
         tmp := WindowsDeleteString (m_hString);
      end return;
   end;

   function Constructor
   (
      handler : WinUI3.Windows.System.Threading.WorkItemHandler;
      priority : WinUI3.Windows.System.Threading.WorkItemPriority;
      options : WinUI3.Windows.System.Threading.WorkItemOptions
   )
   return PreallocatedWorkItem is
      Hr           : WinUI3.HResult := S_OK;
      tmp          : WinUI3.HResult := S_OK;
      m_hString    : constant WinUI3.HString := To_HString ("Windows.System.Threading.Core.IPreallocatedWorkItem");
      m_Factory    : access IPreallocatedWorkItemFactory_Interface'Class := null;
      temp         : WinUI3.UInt32 := 0;
      m_ComRetVal  : aliased WinUI3.Windows.System.Threading.Core.IPreallocatedWorkItem;
   begin
      return RetVal : PreallocatedWorkItem do
         Hr := RoGetActivationFactory (m_hString, IID_IPreallocatedWorkItemFactory'Access , m_Factory'Address);
         if Hr = S_OK then
            Hr := m_Factory.CreateWorkItemWithPriorityAndOptions (handler, priority, options, m_ComRetVal'Access);
            Retval.m_IPreallocatedWorkItem := new WinUI3.Windows.System.Threading.Core.IPreallocatedWorkItem;
            Retval.m_IPreallocatedWorkItem.all := m_ComRetVal;
            temp := m_Factory.Release;
         end if;
         tmp := WindowsDeleteString (m_hString);
      end return;
   end;

   -----------------------------------------------------------------------------
   -- Implemented Interfaces for PreallocatedWorkItem

   procedure RunAsync
   (
      this : in out PreallocatedWorkItem
   ) is
      Hr               : WinUI3.HResult := S_OK;
      tmp              : WinUI3.HResult := S_OK;
      temp             : WinUI3.UInt32 := 0;
      m_Temp           : WinUI3.Int32 := 0;
      m_Completed      : WinUI3.UInt32 := 0;
      m_Captured       : WinUI3.UInt32 := 0;
      m_Compare        : constant WinUI3.UInt32 := 0;
      m_ComRetVal      : aliased WinUI3.Windows.Foundation.IAsyncAction := null;

      procedure IAsyncAction_Callback (asyncInfo : WinUI3.Windows.Foundation.IAsyncAction; asyncStatus: WinUI3.Windows.Foundation.AsyncStatus) is
      begin
         if asyncStatus = Completed_e then
            Hr := asyncInfo.GetResults;
         end if;
         m_Completed := 1;
         WakeByAddressSingle (m_Completed'Address);
      end;

      m_CompletedHandler : WinUI3.Windows.Foundation.AsyncActionCompletedHandler := new WinUI3.Windows.Foundation.AsyncActionCompletedHandler_Delegate'(IAsyncAction_Callback'Access, 1, null);
      procedure Free is new Ada.Unchecked_Deallocation (WinUI3.Windows.Foundation.AsyncActionCompletedHandler_Delegate, WinUI3.Windows.Foundation.AsyncActionCompletedHandler);

   begin
      Hr := this.m_IPreallocatedWorkItem.all.RunAsync (m_ComRetVal'Access);
      if Hr = S_OK then
         m_Captured := m_Completed;
         Hr := m_ComRetVal.Put_Completed (m_CompletedHandler);
         while m_Captured = m_Compare loop
            m_Temp := WaitOnAddress (m_Completed'Address, m_Compare'Address, 4, 4294967295);
            m_Captured := m_Completed;
         end loop;
         temp := m_ComRetVal.Release;
         temp := m_CompletedHandler.Release;
         if temp = 0 then
            Free (m_CompletedHandler);
         end if;
      end if;
   end;

   -----------------------------------------------------------------------------
   -- Delegate SignalHandler

   function Invoke
   (
      this : access SignalHandler_Delegate;
      signalNotifier_p : WinUI3.Windows.System.Threading.Core.ISignalNotifier;
      timedOut : WinUI3.Boolean
   )
   return WinUI3.Hresult is
      Hr : constant WinUI3.HResult := S_OK;
   begin
      this.Callback (signalNotifier_p, timedOut);
      return Hr;
   end;

   -----------------------------------------------------------------------------
   -- RuntimeClass Initialization/Finalization for SignalNotifier

   procedure Initialize (this : in out SignalNotifier) is
   begin
      null;
   end;

   procedure Finalize (this : in out SignalNotifier) is
      temp : WinUI3.UInt32 := 0;
      procedure Free is new Ada.Unchecked_Deallocation (ISignalNotifier, ISignalNotifier_Ptr);
   begin
      if this.m_ISignalNotifier /= null then
         if this.m_ISignalNotifier.all /= null then
            temp := this.m_ISignalNotifier.all.Release;
            Free (this.m_ISignalNotifier);
         end if;
      end if;
   end;

   -----------------------------------------------------------------------------
   -- Static Interfaces for SignalNotifier

   function AttachToEvent
   (
      name : WinUI3.WString;
      handler : WinUI3.Windows.System.Threading.Core.SignalHandler
   )
   return WinUI3.Windows.System.Threading.Core.SignalNotifier is
      Hr               : WinUI3.HResult := S_OK;
      tmp              : WinUI3.HResult := S_OK;
      m_hString        : constant WinUI3.HString := To_HString ("Windows.System.Threading.Core.SignalNotifier");
      m_Factory        : access WinUI3.Windows.System.Threading.Core.ISignalNotifierStatics_Interface'Class := null;
      temp             : WinUI3.UInt32 := 0;
      m_ComRetVal      : aliased WinUI3.Windows.System.Threading.Core.ISignalNotifier;
      HStr_name : constant WinUI3.HString := To_HString (name);
   begin
      return RetVal : WinUI3.Windows.System.Threading.Core.SignalNotifier do
         Hr := RoGetActivationFactory (m_hString, IID_ISignalNotifierStatics'Access , m_Factory'Address);
         if Hr = S_OK then
            Hr := m_Factory.AttachToEvent (HStr_name, handler, m_ComRetVal'Access);
            temp := m_Factory.Release;
            if Hr /= S_OK then
               raise Program_Error;
            end if;
            Retval.m_ISignalNotifier := new WinUI3.Windows.System.Threading.Core.ISignalNotifier;
            Retval.m_ISignalNotifier.all := m_ComRetVal;
         end if;
         tmp := WindowsDeleteString (m_hString);
         tmp := WindowsDeleteString (HStr_name);
      end return;
   end;

   function AttachToEvent
   (
      name : WinUI3.WString;
      handler : WinUI3.Windows.System.Threading.Core.SignalHandler;
      timeout : WinUI3.Windows.Foundation.TimeSpan
   )
   return WinUI3.Windows.System.Threading.Core.SignalNotifier is
      Hr               : WinUI3.HResult := S_OK;
      tmp              : WinUI3.HResult := S_OK;
      m_hString        : constant WinUI3.HString := To_HString ("Windows.System.Threading.Core.SignalNotifier");
      m_Factory        : access WinUI3.Windows.System.Threading.Core.ISignalNotifierStatics_Interface'Class := null;
      temp             : WinUI3.UInt32 := 0;
      m_ComRetVal      : aliased WinUI3.Windows.System.Threading.Core.ISignalNotifier;
      HStr_name : constant WinUI3.HString := To_HString (name);
   begin
      return RetVal : WinUI3.Windows.System.Threading.Core.SignalNotifier do
         Hr := RoGetActivationFactory (m_hString, IID_ISignalNotifierStatics'Access , m_Factory'Address);
         if Hr = S_OK then
            Hr := m_Factory.AttachToEvent (HStr_name, handler, timeout, m_ComRetVal'Access);
            temp := m_Factory.Release;
            if Hr /= S_OK then
               raise Program_Error;
            end if;
            Retval.m_ISignalNotifier := new WinUI3.Windows.System.Threading.Core.ISignalNotifier;
            Retval.m_ISignalNotifier.all := m_ComRetVal;
         end if;
         tmp := WindowsDeleteString (m_hString);
         tmp := WindowsDeleteString (HStr_name);
      end return;
   end;

   function AttachToSemaphore
   (
      name : WinUI3.WString;
      handler : WinUI3.Windows.System.Threading.Core.SignalHandler
   )
   return WinUI3.Windows.System.Threading.Core.SignalNotifier is
      Hr               : WinUI3.HResult := S_OK;
      tmp              : WinUI3.HResult := S_OK;
      m_hString        : constant WinUI3.HString := To_HString ("Windows.System.Threading.Core.SignalNotifier");
      m_Factory        : access WinUI3.Windows.System.Threading.Core.ISignalNotifierStatics_Interface'Class := null;
      temp             : WinUI3.UInt32 := 0;
      m_ComRetVal      : aliased WinUI3.Windows.System.Threading.Core.ISignalNotifier;
      HStr_name : constant WinUI3.HString := To_HString (name);
   begin
      return RetVal : WinUI3.Windows.System.Threading.Core.SignalNotifier do
         Hr := RoGetActivationFactory (m_hString, IID_ISignalNotifierStatics'Access , m_Factory'Address);
         if Hr = S_OK then
            Hr := m_Factory.AttachToSemaphore (HStr_name, handler, m_ComRetVal'Access);
            temp := m_Factory.Release;
            if Hr /= S_OK then
               raise Program_Error;
            end if;
            Retval.m_ISignalNotifier := new WinUI3.Windows.System.Threading.Core.ISignalNotifier;
            Retval.m_ISignalNotifier.all := m_ComRetVal;
         end if;
         tmp := WindowsDeleteString (m_hString);
         tmp := WindowsDeleteString (HStr_name);
      end return;
   end;

   function AttachToSemaphore
   (
      name : WinUI3.WString;
      handler : WinUI3.Windows.System.Threading.Core.SignalHandler;
      timeout : WinUI3.Windows.Foundation.TimeSpan
   )
   return WinUI3.Windows.System.Threading.Core.SignalNotifier is
      Hr               : WinUI3.HResult := S_OK;
      tmp              : WinUI3.HResult := S_OK;
      m_hString        : constant WinUI3.HString := To_HString ("Windows.System.Threading.Core.SignalNotifier");
      m_Factory        : access WinUI3.Windows.System.Threading.Core.ISignalNotifierStatics_Interface'Class := null;
      temp             : WinUI3.UInt32 := 0;
      m_ComRetVal      : aliased WinUI3.Windows.System.Threading.Core.ISignalNotifier;
      HStr_name : constant WinUI3.HString := To_HString (name);
   begin
      return RetVal : WinUI3.Windows.System.Threading.Core.SignalNotifier do
         Hr := RoGetActivationFactory (m_hString, IID_ISignalNotifierStatics'Access , m_Factory'Address);
         if Hr = S_OK then
            Hr := m_Factory.AttachToSemaphore (HStr_name, handler, timeout, m_ComRetVal'Access);
            temp := m_Factory.Release;
            if Hr /= S_OK then
               raise Program_Error;
            end if;
            Retval.m_ISignalNotifier := new WinUI3.Windows.System.Threading.Core.ISignalNotifier;
            Retval.m_ISignalNotifier.all := m_ComRetVal;
         end if;
         tmp := WindowsDeleteString (m_hString);
         tmp := WindowsDeleteString (HStr_name);
      end return;
   end;

   -----------------------------------------------------------------------------
   -- Implemented Interfaces for SignalNotifier

   procedure Enable
   (
      this : in out SignalNotifier
   ) is
      Hr               : WinUI3.HResult := S_OK;
      tmp              : WinUI3.HResult := S_OK;
      temp             : WinUI3.UInt32 := 0;
   begin
      Hr := this.m_ISignalNotifier.all.Enable;
      if Hr /= S_OK then
         raise Program_Error;
      end if;
   end;

   procedure Terminate_x
   (
      this : in out SignalNotifier
   ) is
      Hr               : WinUI3.HResult := S_OK;
      tmp              : WinUI3.HResult := S_OK;
      temp             : WinUI3.UInt32 := 0;
   begin
      Hr := this.m_ISignalNotifier.all.Terminate_x;
      if Hr /= S_OK then
         raise Program_Error;
      end if;
   end;

end WinUI3.Windows.System.Threading.Core;
