--------------------------------------------------------------------------------
-- <auto-generated>                                                           --
--     This code was generated by a tool.                                     --
--                                                                            --
--     Changes to this file may cause incorrect behavior and will be lost if  --
--     the code is regenerated.                                               --
-- </auto-generated>                                                          --
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--                                                                            --
--    Copyright(c) 2023 Alexander Gamper, All Rights Reserved.                --
--                                                                            --
--    Ada-WinRT                                                               --
--    Version   : 3.0.0.0                                                     --
--                                                                            --
-- This program is free software: you can redistribute it and / or modify     --
-- it under the terms of the GNU Lesser General Public License as published by--
-- the Free Software Foundation, either version 3 of the License, or          --
-- (at your option) any later version.                                        --
--                                                                            --
-- This program is distributed in the hope that it will be useful,            --
-- but WITHOUT ANY WARRANTY; without even the implied warranty of             --
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the               --
-- GNU Lesser General Public License for more details.                        --
--                                                                            --
-- You should have received a copy of the GNU Lesser General Public License   --
-- along with this program.If not, see http://www.gnu.org/licenses            --
--                                                                            --
--------------------------------------------------------------------------------
with WinRt.Windows.Foundation;
with WinRt.Windows.Foundation.Collections;
with Ada.Finalization;
--------------------------------------------------------------------------------
package WinRt.Windows.Data.Json is

   pragma PreElaborate;

   -----------------------------------------------------------------------------
   -- Forward Interface declarations
   -----------------------------------------------------------------------------

   type IJsonArray_Interface is interface and WinRt.IInspectable_Interface;
   type IJsonArray is access all IJsonArray_Interface'Class;
   type IJsonArray_Ptr is access all IJsonArray;

   type IJsonArrayStatics_Interface is interface and WinRt.IInspectable_Interface;
   type IJsonArrayStatics is access all IJsonArrayStatics_Interface'Class;

   type IJsonErrorStatics2_Interface is interface and WinRt.IInspectable_Interface;
   type IJsonErrorStatics2 is access all IJsonErrorStatics2_Interface'Class;

   type IJsonObject_Interface is interface and WinRt.IInspectable_Interface;
   type IJsonObject is access all IJsonObject_Interface'Class;
   type IJsonObject_Ptr is access all IJsonObject;

   type IJsonObjectStatics_Interface is interface and WinRt.IInspectable_Interface;
   type IJsonObjectStatics is access all IJsonObjectStatics_Interface'Class;

   type IJsonObjectWithDefaultValues_Interface is interface and WinRt.IInspectable_Interface;
   type IJsonObjectWithDefaultValues is access all IJsonObjectWithDefaultValues_Interface'Class;

   type IJsonValue_Interface is interface and WinRt.IInspectable_Interface;
   type IJsonValue is access all IJsonValue_Interface'Class;
   type IJsonValue_Ptr is access all IJsonValue;
   type IJsonValue_Array is array (Natural range <>) of IJsonValue;

   type IJsonValueStatics_Interface is interface and WinRt.IInspectable_Interface;
   type IJsonValueStatics is access all IJsonValueStatics_Interface'Class;

   type IJsonValueStatics2_Interface is interface and WinRt.IInspectable_Interface;
   type IJsonValueStatics2 is access all IJsonValueStatics2_Interface'Class;

   -----------------------------------------------------------------------------
   -- Class declarations
   -----------------------------------------------------------------------------

   type JsonArray is new Ada.Finalization.Limited_Controlled with
      record
         m_IJsonArray : access Windows.Data.Json.IJsonArray;
      end record;
   type JsonArray_Ptr is access all JsonArray;

   type JsonObject is new Ada.Finalization.Limited_Controlled with
      record
         m_IJsonObject : access Windows.Data.Json.IJsonObject;
      end record;
   type JsonObject_Ptr is access all JsonObject;

   type JsonValue is new Ada.Finalization.Limited_Controlled with
      record
         m_IJsonValue : access Windows.Data.Json.IJsonValue;
      end record;
   type JsonValue_Ptr is access all JsonValue;

   -----------------------------------------------------------------------------
   -- Enum declarations
   -----------------------------------------------------------------------------

   type JsonErrorStatus is (
      Unknown_e,
      InvalidJsonString_e,
      InvalidJsonNumber_e,
      JsonValueNotFound_e,
      ImplementationLimit_e
   );
   for JsonErrorStatus use (
      Unknown_e => 0,
      InvalidJsonString_e => 1,
      InvalidJsonNumber_e => 2,
      JsonValueNotFound_e => 3,
      ImplementationLimit_e => 4
   );
   type JsonErrorStatus_Ptr is access all JsonErrorStatus;

   type JsonValueType is (
      Null_e,
      Boolean_e,
      Number_e,
      String_e,
      Array_e,
      Object_e
   );
   for JsonValueType use (
      Null_e => 0,
      Boolean_e => 1,
      Number_e => 2,
      String_e => 3,
      Array_e => 4,
      Object_e => 5
   );
   type JsonValueType_Ptr is access all JsonValueType;

   -----------------------------------------------------------------------------
   -- Generic package declarations
   -----------------------------------------------------------------------------

   -----------------------------------------------------------------------------
   -- Interface declarations
   -----------------------------------------------------------------------------

   -----------------------------------------------------------------------------
   -- type IJsonArray is interface and WinRt.IInspectable;

      function GetObjectAt
      (
         this : access IJsonArray_Interface;
         index : WinRt.UInt32;
         RetVal : access Windows.Data.Json.IJsonObject
      )
      return WinRt.Hresult is abstract;

      function GetArrayAt
      (
         this : access IJsonArray_Interface;
         index : WinRt.UInt32;
         RetVal : access Windows.Data.Json.IJsonArray
      )
      return WinRt.Hresult is abstract;

      function GetStringAt
      (
         this : access IJsonArray_Interface;
         index : WinRt.UInt32;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      function GetNumberAt
      (
         this : access IJsonArray_Interface;
         index : WinRt.UInt32;
         RetVal : access WinRt.Double
      )
      return WinRt.Hresult is abstract;

      function GetBooleanAt
      (
         this : access IJsonArray_Interface;
         index : WinRt.UInt32;
         RetVal : access WinRt.Boolean
      )
      return WinRt.Hresult is abstract;

      IID_IJsonArray : aliased WinRt.IID := (146922934, 3261, 19098, (181, 211, 47, 133, 45, 195, 126, 129 ));

   -----------------------------------------------------------------------------
   -- type IJsonArrayStatics is interface and WinRt.IInspectable;

      function Parse
      (
         this : access IJsonArrayStatics_Interface;
         input : WinRt.HString;
         RetVal : access Windows.Data.Json.IJsonArray
      )
      return WinRt.Hresult is abstract;

      function TryParse
      (
         this : access IJsonArrayStatics_Interface;
         input : WinRt.HString;
         result : access Windows.Data.Json.IJsonArray;
         RetVal : access WinRt.Boolean
      )
      return WinRt.Hresult is abstract;

      IID_IJsonArrayStatics : aliased WinRt.IID := (3675534505, 57700, 18847, (147, 226, 138, 143, 73, 187, 144, 186 ));

   -----------------------------------------------------------------------------
   -- type IJsonErrorStatics2 is interface and WinRt.IInspectable;

      function GetJsonStatus
      (
         this : access IJsonErrorStatics2_Interface;
         hresult : WinRt.Int32;
         RetVal : access Windows.Data.Json.JsonErrorStatus
      )
      return WinRt.Hresult is abstract;

      IID_IJsonErrorStatics2 : aliased WinRt.IID := (1077948634, 34768, 17260, (131, 171, 252, 123, 18, 192, 204, 38 ));

   -----------------------------------------------------------------------------
   -- type IJsonObject is interface and WinRt.IInspectable;

      function GetNamedValue
      (
         this : access IJsonObject_Interface;
         name : WinRt.HString;
         RetVal : access Windows.Data.Json.IJsonValue
      )
      return WinRt.Hresult is abstract;

      function SetNamedValue
      (
         this : access IJsonObject_Interface;
         name : WinRt.HString;
         value : Windows.Data.Json.IJsonValue
      )
      return WinRt.Hresult is abstract;

      function GetNamedObject
      (
         this : access IJsonObject_Interface;
         name : WinRt.HString;
         RetVal : access Windows.Data.Json.IJsonObject
      )
      return WinRt.Hresult is abstract;

      function GetNamedArray
      (
         this : access IJsonObject_Interface;
         name : WinRt.HString;
         RetVal : access Windows.Data.Json.IJsonArray
      )
      return WinRt.Hresult is abstract;

      function GetNamedString
      (
         this : access IJsonObject_Interface;
         name : WinRt.HString;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      function GetNamedNumber
      (
         this : access IJsonObject_Interface;
         name : WinRt.HString;
         RetVal : access WinRt.Double
      )
      return WinRt.Hresult is abstract;

      function GetNamedBoolean
      (
         this : access IJsonObject_Interface;
         name : WinRt.HString;
         RetVal : access WinRt.Boolean
      )
      return WinRt.Hresult is abstract;

      IID_IJsonObject : aliased WinRt.IID := (105784541, 10690, 20355, (154, 193, 158, 225, 21, 120, 190, 179 ));

   -----------------------------------------------------------------------------
   -- type IJsonObjectStatics is interface and WinRt.IInspectable;

      function Parse
      (
         this : access IJsonObjectStatics_Interface;
         input : WinRt.HString;
         RetVal : access Windows.Data.Json.IJsonObject
      )
      return WinRt.Hresult is abstract;

      function TryParse
      (
         this : access IJsonObjectStatics_Interface;
         input : WinRt.HString;
         result : access Windows.Data.Json.IJsonObject;
         RetVal : access WinRt.Boolean
      )
      return WinRt.Hresult is abstract;

      IID_IJsonObjectStatics : aliased WinRt.IID := (579465561, 21726, 17880, (171, 204, 34, 96, 63, 160, 102, 160 ));

   -----------------------------------------------------------------------------
   -- type IJsonObjectWithDefaultValues is interface and WinRt.IInspectable;

      function GetNamedValue
      (
         this : access IJsonObjectWithDefaultValues_Interface;
         name : WinRt.HString;
         defaultValue : Windows.Data.Json.IJsonValue;
         RetVal : access Windows.Data.Json.IJsonValue
      )
      return WinRt.Hresult is abstract;

      function GetNamedObject
      (
         this : access IJsonObjectWithDefaultValues_Interface;
         name : WinRt.HString;
         defaultValue : Windows.Data.Json.IJsonObject;
         RetVal : access Windows.Data.Json.IJsonObject
      )
      return WinRt.Hresult is abstract;

      function GetNamedString
      (
         this : access IJsonObjectWithDefaultValues_Interface;
         name : WinRt.HString;
         defaultValue : WinRt.HString;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      function GetNamedArray
      (
         this : access IJsonObjectWithDefaultValues_Interface;
         name : WinRt.HString;
         defaultValue : Windows.Data.Json.IJsonArray;
         RetVal : access Windows.Data.Json.IJsonArray
      )
      return WinRt.Hresult is abstract;

      function GetNamedNumber
      (
         this : access IJsonObjectWithDefaultValues_Interface;
         name : WinRt.HString;
         defaultValue : WinRt.Double;
         RetVal : access WinRt.Double
      )
      return WinRt.Hresult is abstract;

      function GetNamedBoolean
      (
         this : access IJsonObjectWithDefaultValues_Interface;
         name : WinRt.HString;
         defaultValue : WinRt.Boolean;
         RetVal : access WinRt.Boolean
      )
      return WinRt.Hresult is abstract;

      IID_IJsonObjectWithDefaultValues : aliased WinRt.IID := (3647001250, 47088, 20224, (142, 68, 216, 44, 244, 21, 234, 19 ));

   -----------------------------------------------------------------------------
   -- type IJsonValue is interface and WinRt.IInspectable;

      function get_ValueType
      (
         this : access IJsonValue_Interface;
         RetVal : access Windows.Data.Json.JsonValueType
      )
      return WinRt.Hresult is abstract;

      function Stringify
      (
         this : access IJsonValue_Interface;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      function GetString
      (
         this : access IJsonValue_Interface;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      function GetNumber
      (
         this : access IJsonValue_Interface;
         RetVal : access WinRt.Double
      )
      return WinRt.Hresult is abstract;

      function GetBoolean
      (
         this : access IJsonValue_Interface;
         RetVal : access WinRt.Boolean
      )
      return WinRt.Hresult is abstract;

      function GetArray
      (
         this : access IJsonValue_Interface;
         RetVal : access Windows.Data.Json.IJsonArray
      )
      return WinRt.Hresult is abstract;

      function GetObject
      (
         this : access IJsonValue_Interface;
         RetVal : access Windows.Data.Json.IJsonObject
      )
      return WinRt.Hresult is abstract;

      IID_IJsonValue : aliased WinRt.IID := (2736889547, 61619, 19917, (190, 238, 25, 212, 140, 211, 237, 30 ));

   -----------------------------------------------------------------------------
   -- type IJsonValueStatics is interface and WinRt.IInspectable;

      function Parse
      (
         this : access IJsonValueStatics_Interface;
         input : WinRt.HString;
         RetVal : access Windows.Data.Json.IJsonValue
      )
      return WinRt.Hresult is abstract;

      function TryParse
      (
         this : access IJsonValueStatics_Interface;
         input : WinRt.HString;
         result : access Windows.Data.Json.IJsonValue;
         RetVal : access WinRt.Boolean
      )
      return WinRt.Hresult is abstract;

      function CreateBooleanValue
      (
         this : access IJsonValueStatics_Interface;
         input : WinRt.Boolean;
         RetVal : access Windows.Data.Json.IJsonValue
      )
      return WinRt.Hresult is abstract;

      function CreateNumberValue
      (
         this : access IJsonValueStatics_Interface;
         input : WinRt.Double;
         RetVal : access Windows.Data.Json.IJsonValue
      )
      return WinRt.Hresult is abstract;

      function CreateStringValue
      (
         this : access IJsonValueStatics_Interface;
         input : WinRt.HString;
         RetVal : access Windows.Data.Json.IJsonValue
      )
      return WinRt.Hresult is abstract;

      IID_IJsonValueStatics : aliased WinRt.IID := (1600869450, 12115, 18657, (145, 163, 247, 139, 80, 166, 52, 92 ));

   -----------------------------------------------------------------------------
   -- type IJsonValueStatics2 is interface and WinRt.IInspectable;

      function CreateNullValue
      (
         this : access IJsonValueStatics2_Interface;
         RetVal : access Windows.Data.Json.IJsonValue
      )
      return WinRt.Hresult is abstract;

      IID_IJsonValueStatics2 : aliased WinRt.IID := (496946148, 16360, 17205, (131, 146, 147, 216, 227, 104, 101, 240 ));

   -----------------------------------------------------------------------------
   -- Class method declarations
   -----------------------------------------------------------------------------

   -----------------------------------------------------------------------------
   -- RuntimeClass Initialization/Finalization for JsonArray

   overriding procedure Initialize (this : in out JsonArray);
   overriding procedure Finalize (this : in out JsonArray);

   -----------------------------------------------------------------------------
   -- RuntimeClass Constructors for JsonArray

   function Constructor return JsonArray;

   -----------------------------------------------------------------------------
   -- Static Interfaces for JsonArray

   function Parse
   (
      input : WinRt.WString
   )
   return WinRt.Windows.Data.Json.JsonArray;

   function TryParse
   (
      input : WinRt.WString;
      result : access Windows.Data.Json.IJsonArray
   )
   return WinRt.Boolean;

   -----------------------------------------------------------------------------
   -- Implemented Interfaces for JsonArray

   function GetObjectAt
   (
      this : in out JsonArray;
      index : WinRt.UInt32
   )
   return WinRt.Windows.Data.Json.JsonObject'Class;

   function GetArrayAt
   (
      this : in out JsonArray;
      index : WinRt.UInt32
   )
   return WinRt.Windows.Data.Json.JsonArray'Class;

   function GetStringAt
   (
      this : in out JsonArray;
      index : WinRt.UInt32
   )
   return WinRt.WString;

   function GetNumberAt
   (
      this : in out JsonArray;
      index : WinRt.UInt32
   )
   return WinRt.Double;

   function GetBooleanAt
   (
      this : in out JsonArray;
      index : WinRt.UInt32
   )
   return WinRt.Boolean;

   function get_ValueType
   (
      this : in out JsonArray
   )
   return WinRt.Windows.Data.Json.JsonValueType;

   function Stringify
   (
      this : in out JsonArray
   )
   return WinRt.WString;

   function GetString
   (
      this : in out JsonArray
   )
   return WinRt.WString;

   function GetNumber
   (
      this : in out JsonArray
   )
   return WinRt.Double;

   function GetBoolean
   (
      this : in out JsonArray
   )
   return WinRt.Boolean;

   function GetArray
   (
      this : in out JsonArray
   )
   return WinRt.Windows.Data.Json.JsonArray'Class;

   function GetObject
   (
      this : in out JsonArray
   )
   return WinRt.Windows.Data.Json.JsonObject'Class;

   -- Generic Interface Windows.Foundation.Collections.IVector`1<Windows.Data.Json.IJsonValue>
   function GetAt
   (
      this : in out JsonArray;
      index : WinRt.UInt32
   )
   return WinRt.Windows.Data.Json.IJsonValue;

   function get_Size
   (
      this : in out JsonArray
   )
   return WinRt.UInt32;

   function GetView
   (
      this : in out JsonArray
   )
   return WinRt.Windows.Data.Json.IJsonValue;

   function IndexOf
   (
      this : in out JsonArray;
      value : Windows.Data.Json.IJsonValue;
      index : WinRt.UInt32_Ptr
   )
   return WinRt.Boolean;

   procedure SetAt
   (
      this : in out JsonArray;
      index : WinRt.UInt32;
      value : Windows.Data.Json.IJsonValue
   );

   procedure InsertAt
   (
      this : in out JsonArray;
      index : WinRt.UInt32;
      value : Windows.Data.Json.IJsonValue
   );

   procedure RemoveAt
   (
      this : in out JsonArray;
      index : WinRt.UInt32
   );

   procedure Append
   (
      this : in out JsonArray;
      value : Windows.Data.Json.IJsonValue
   );

   procedure RemoveAtEnd
   (
      this : in out JsonArray
   );

   procedure Clear
   (
      this : in out JsonArray
   );

   function GetMany
   (
      this : in out JsonArray;
      startIndex : WinRt.UInt32;
      items : Windows.Data.Json.IJsonValue_Array
   )
   return WinRt.UInt32;

   procedure ReplaceAll
   (
      this : in out JsonArray;
      items : Windows.Data.Json.IJsonValue_Array
   );

   -- Generic Interface Windows.Foundation.Collections.IIterable`1<Windows.Data.Json.IJsonValue>
   function First
   (
      this : in out JsonArray
   )
   return WinRt.Windows.Data.Json.IJsonValue;

   function ToString
   (
      this : in out JsonArray
   )
   return WinRt.WString;

   -----------------------------------------------------------------------------
   -- Static RuntimeClass
   package JsonError is

      function GetJsonStatus
      (
         hresult : WinRt.Int32
      )
      return WinRt.Windows.Data.Json.JsonErrorStatus;

   end JsonError;

   -----------------------------------------------------------------------------
   -- RuntimeClass Initialization/Finalization for JsonObject

   overriding procedure Initialize (this : in out JsonObject);
   overriding procedure Finalize (this : in out JsonObject);

   -----------------------------------------------------------------------------
   -- RuntimeClass Constructors for JsonObject

   function Constructor return JsonObject;

   -----------------------------------------------------------------------------
   -- Static Interfaces for JsonObject

   function Parse
   (
      input : WinRt.WString
   )
   return WinRt.Windows.Data.Json.JsonObject;

   function TryParse
   (
      input : WinRt.WString;
      result : access Windows.Data.Json.IJsonObject
   )
   return WinRt.Boolean;

   -----------------------------------------------------------------------------
   -- Implemented Interfaces for JsonObject

   function GetNamedValue
   (
      this : in out JsonObject;
      name : WinRt.WString
   )
   return WinRt.Windows.Data.Json.JsonValue'Class;

   procedure SetNamedValue
   (
      this : in out JsonObject;
      name : WinRt.WString;
      value : Windows.Data.Json.IJsonValue
   );

   function GetNamedObject
   (
      this : in out JsonObject;
      name : WinRt.WString
   )
   return WinRt.Windows.Data.Json.JsonObject'Class;

   function GetNamedArray
   (
      this : in out JsonObject;
      name : WinRt.WString
   )
   return WinRt.Windows.Data.Json.JsonArray'Class;

   function GetNamedString
   (
      this : in out JsonObject;
      name : WinRt.WString
   )
   return WinRt.WString;

   function GetNamedNumber
   (
      this : in out JsonObject;
      name : WinRt.WString
   )
   return WinRt.Double;

   function GetNamedBoolean
   (
      this : in out JsonObject;
      name : WinRt.WString
   )
   return WinRt.Boolean;

   function get_ValueType
   (
      this : in out JsonObject
   )
   return WinRt.Windows.Data.Json.JsonValueType;

   function Stringify
   (
      this : in out JsonObject
   )
   return WinRt.WString;

   function GetString
   (
      this : in out JsonObject
   )
   return WinRt.WString;

   function GetNumber
   (
      this : in out JsonObject
   )
   return WinRt.Double;

   function GetBoolean
   (
      this : in out JsonObject
   )
   return WinRt.Boolean;

   function GetArray
   (
      this : in out JsonObject
   )
   return WinRt.Windows.Data.Json.JsonArray'Class;

   function GetObject
   (
      this : in out JsonObject
   )
   return WinRt.Windows.Data.Json.JsonObject'Class;

   -- Generic Interface Windows.Foundation.Collections.IMap`2<System.String,Windows.Data.Json.IJsonValue>
   function Lookup
   (
      this : in out JsonObject;
      key : WinRt.WString
   )
   return WinRt.Windows.Data.Json.IJsonValue;

   function get_Size
   (
      this : in out JsonObject
   )
   return WinRt.UInt32;

   function HasKey
   (
      this : in out JsonObject;
      key : WinRt.WString
   )
   return WinRt.Boolean;

   function GetView
   (
      this : in out JsonObject
   )
   return WinRt.GenericObject;

   function Insert
   (
      this : in out JsonObject;
      key : WinRt.WString;
      value : Windows.Data.Json.IJsonValue
   )
   return WinRt.Boolean;

   procedure Remove
   (
      this : in out JsonObject;
      key : WinRt.WString
   );

   procedure Clear
   (
      this : in out JsonObject
   );

   function GetNamedValue
   (
      this : in out JsonObject;
      name : WinRt.WString;
      defaultValue : Windows.Data.Json.JsonValue'Class
   )
   return WinRt.Windows.Data.Json.JsonValue'Class;

   function GetNamedObject
   (
      this : in out JsonObject;
      name : WinRt.WString;
      defaultValue : Windows.Data.Json.JsonObject'Class
   )
   return WinRt.Windows.Data.Json.JsonObject'Class;

   function GetNamedString
   (
      this : in out JsonObject;
      name : WinRt.WString;
      defaultValue : WinRt.WString
   )
   return WinRt.WString;

   function GetNamedArray
   (
      this : in out JsonObject;
      name : WinRt.WString;
      defaultValue : Windows.Data.Json.JsonArray'Class
   )
   return WinRt.Windows.Data.Json.JsonArray'Class;

   function GetNamedNumber
   (
      this : in out JsonObject;
      name : WinRt.WString;
      defaultValue : WinRt.Double
   )
   return WinRt.Double;

   function GetNamedBoolean
   (
      this : in out JsonObject;
      name : WinRt.WString;
      defaultValue : WinRt.Boolean
   )
   return WinRt.Boolean;

   function ToString
   (
      this : in out JsonObject
   )
   return WinRt.WString;

   -----------------------------------------------------------------------------
   -- RuntimeClass Initialization/Finalization for JsonValue

   overriding procedure Initialize (this : in out JsonValue);
   overriding procedure Finalize (this : in out JsonValue);

   -----------------------------------------------------------------------------
   -- Static Interfaces for JsonValue

   function Parse
   (
      input : WinRt.WString
   )
   return WinRt.Windows.Data.Json.JsonValue;

   function TryParse
   (
      input : WinRt.WString;
      result : access Windows.Data.Json.IJsonValue
   )
   return WinRt.Boolean;

   function CreateBooleanValue
   (
      input : WinRt.Boolean
   )
   return WinRt.Windows.Data.Json.JsonValue;

   function CreateNumberValue
   (
      input : WinRt.Double
   )
   return WinRt.Windows.Data.Json.JsonValue;

   function CreateStringValue
   (
      input : WinRt.WString
   )
   return WinRt.Windows.Data.Json.JsonValue;

   function CreateNullValue
   return WinRt.Windows.Data.Json.JsonValue;

   -----------------------------------------------------------------------------
   -- Implemented Interfaces for JsonValue

   function get_ValueType
   (
      this : in out JsonValue
   )
   return WinRt.Windows.Data.Json.JsonValueType;

   function Stringify
   (
      this : in out JsonValue
   )
   return WinRt.WString;

   function GetString
   (
      this : in out JsonValue
   )
   return WinRt.WString;

   function GetNumber
   (
      this : in out JsonValue
   )
   return WinRt.Double;

   function GetBoolean
   (
      this : in out JsonValue
   )
   return WinRt.Boolean;

   function GetArray
   (
      this : in out JsonValue
   )
   return WinRt.Windows.Data.Json.JsonArray'Class;

   function GetObject
   (
      this : in out JsonValue
   )
   return WinRt.Windows.Data.Json.JsonObject'Class;

   function ToString
   (
      this : in out JsonValue
   )
   return WinRt.WString;

end WinRt.Windows.Data.Json;
