--------------------------------------------------------------------------------
-- <auto-generated>                                                           --
--     This code was generated by a tool.                                     --
--                                                                            --
--     Changes to this file may cause incorrect behavior and will be lost if  --
--     the code is regenerated.                                               --
-- </auto-generated>                                                          --
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--                                                                            --
--    Copyright(c) 2023 Alexander Gamper, All Rights Reserved.                --
--                                                                            --
--    Ada-WinRT                                                               --
--    Version   : 3.0.0.0                                                     --
--                                                                            --
-- This program is free software: you can redistribute it and / or modify     --
-- it under the terms of the GNU Lesser General Public License as published by--
-- the Free Software Foundation, either version 3 of the License, or          --
-- (at your option) any later version.                                        --
--                                                                            --
-- This program is distributed in the hope that it will be useful,            --
-- but WITHOUT ANY WARRANTY; without even the implied warranty of             --
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the               --
-- GNU Lesser General Public License for more details.                        --
--                                                                            --
-- You should have received a copy of the GNU Lesser General Public License   --
-- along with this program.If not, see http://www.gnu.org/licenses            --
--                                                                            --
--------------------------------------------------------------------------------
with WinRt.Windows.Foundation; use WinRt.Windows.Foundation;
with Ada.Unchecked_Conversion;
with Ada.Unchecked_Deallocation;
--------------------------------------------------------------------------------
package body WinRt.Windows.Phone.Devices.Power is

   -----------------------------------------------------------------------------
   -- RuntimeClass Initialization/Finalization for Battery

   procedure Initialize (this : in out Battery) is
   begin
      null;
   end;

   procedure Finalize (this : in out Battery) is
      RefCount : WinRt.UInt32 := 0;
      procedure Free is new Ada.Unchecked_Deallocation (IBattery, IBattery_Ptr);
   begin
      if this.m_IBattery /= null then
         if this.m_IBattery.all /= null then
            RefCount := this.m_IBattery.all.Release;
            Free (this.m_IBattery);
         end if;
      end if;
   end;

   -----------------------------------------------------------------------------
   -- Static Interfaces for Battery

   function GetDefault
   return WinRt.Windows.Phone.Devices.Power.Battery is
      Hr               : WinRt.HResult := S_OK;
      m_hString        : WinRt.HString := To_HString ("Windows.Phone.Devices.Power.Battery");
      m_Factory        : access WinRt.Windows.Phone.Devices.Power.IBatteryStatics_Interface'Class := null;
      m_RefCount       : WinRt.UInt32 := 0;
      m_ComRetVal      : aliased Windows.Phone.Devices.Power.IBattery;
   begin
      return RetVal : WinRt.Windows.Phone.Devices.Power.Battery do
         Hr := RoGetActivationFactory (m_hString, IID_IBatteryStatics'Access , m_Factory'Address);
         if Hr = S_OK then
            Hr := m_Factory.GetDefault (m_ComRetVal'Access);
            m_RefCount := m_Factory.Release;
            Retval.m_IBattery := new Windows.Phone.Devices.Power.IBattery;
            Retval.m_IBattery.all := m_ComRetVal;
         end if;
         Hr := WindowsDeleteString (m_hString);
      end return;
   end;

   -----------------------------------------------------------------------------
   -- Implemented Interfaces for Battery

   function get_RemainingChargePercent
   (
      this : in out Battery
   )
   return WinRt.Int32 is
      Hr               : WinRt.HResult := S_OK;
      m_RefCount       : WinRt.UInt32 := 0;
      m_ComRetVal      : aliased WinRt.Int32;
   begin
      Hr := this.m_IBattery.all.get_RemainingChargePercent (m_ComRetVal'Access);
      return m_ComRetVal;
   end;

   function get_RemainingDischargeTime
   (
      this : in out Battery
   )
   return WinRt.Windows.Foundation.TimeSpan is
      Hr               : WinRt.HResult := S_OK;
      m_RefCount       : WinRt.UInt32 := 0;
      m_ComRetVal      : aliased Windows.Foundation.TimeSpan;
   begin
      Hr := this.m_IBattery.all.get_RemainingDischargeTime (m_ComRetVal'Access);
      return m_ComRetVal;
   end;

   function add_RemainingChargePercentChanged
   (
      this : in out Battery;
      changeHandler : GenericObject
   )
   return WinRt.Windows.Foundation.EventRegistrationToken is
      Hr               : WinRt.HResult := S_OK;
      m_RefCount       : WinRt.UInt32 := 0;
      m_ComRetVal      : aliased Windows.Foundation.EventRegistrationToken;
   begin
      Hr := this.m_IBattery.all.add_RemainingChargePercentChanged (changeHandler, m_ComRetVal'Access);
      return m_ComRetVal;
   end;

   procedure remove_RemainingChargePercentChanged
   (
      this : in out Battery;
      token : Windows.Foundation.EventRegistrationToken
   ) is
      Hr               : WinRt.HResult := S_OK;
      m_RefCount       : WinRt.UInt32 := 0;
   begin
      Hr := this.m_IBattery.all.remove_RemainingChargePercentChanged (token);
   end;

end WinRt.Windows.Phone.Devices.Power;
