--------------------------------------------------------------------------------
-- <auto-generated>                                                           --
--     This code was generated by a tool.                                     --
--                                                                            --
--     Changes to this file may cause incorrect behavior and will be lost if  --
--     the code is regenerated.                                               --
-- </auto-generated>                                                          --
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--                                                                            --
--    Copyright(c) 2023 Alexander Gamper, All Rights Reserved.                --
--                                                                            --
--    Ada-WinRT                                                               --
--    Version   : 3.0.0.0                                                     --
--                                                                            --
-- This program is free software: you can redistribute it and / or modify     --
-- it under the terms of the GNU Lesser General Public License as published by--
-- the Free Software Foundation, either version 3 of the License, or          --
-- (at your option) any later version.                                        --
--                                                                            --
-- This program is distributed in the hope that it will be useful,            --
-- but WITHOUT ANY WARRANTY; without even the implied warranty of             --
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the               --
-- GNU Lesser General Public License for more details.                        --
--                                                                            --
-- You should have received a copy of the GNU Lesser General Public License   --
-- along with this program.If not, see http://www.gnu.org/licenses            --
--                                                                            --
--------------------------------------------------------------------------------
with WinRt.Windows.Foundation;
limited with WinRt.Windows.System;
with Ada.Finalization;
--------------------------------------------------------------------------------
package WinRt.Windows.Security.Authentication.OnlineId is

   pragma PreElaborate;

   -----------------------------------------------------------------------------
   -- Forward Interface declarations
   -----------------------------------------------------------------------------

   type IOnlineIdAuthenticator_Interface is interface and WinRt.IInspectable_Interface;
   type IOnlineIdAuthenticator is access all IOnlineIdAuthenticator_Interface'Class;
   type IOnlineIdAuthenticator_Ptr is access all IOnlineIdAuthenticator;

   type IOnlineIdServiceTicket_Interface is interface and WinRt.IInspectable_Interface;
   type IOnlineIdServiceTicket is access all IOnlineIdServiceTicket_Interface'Class;
   type IOnlineIdServiceTicket_Ptr is access all IOnlineIdServiceTicket;

   type IOnlineIdServiceTicketRequest_Interface is interface and WinRt.IInspectable_Interface;
   type IOnlineIdServiceTicketRequest is access all IOnlineIdServiceTicketRequest_Interface'Class;
   type IOnlineIdServiceTicketRequest_Ptr is access all IOnlineIdServiceTicketRequest;

   type IOnlineIdServiceTicketRequestFactory_Interface is interface and WinRt.IInspectable_Interface;
   type IOnlineIdServiceTicketRequestFactory is access all IOnlineIdServiceTicketRequestFactory_Interface'Class;
   type IOnlineIdServiceTicketRequestFactory_Ptr is access all IOnlineIdServiceTicketRequestFactory;

   type IOnlineIdSystemAuthenticatorForUser_Interface is interface and WinRt.IInspectable_Interface;
   type IOnlineIdSystemAuthenticatorForUser is access all IOnlineIdSystemAuthenticatorForUser_Interface'Class;
   type IOnlineIdSystemAuthenticatorForUser_Ptr is access all IOnlineIdSystemAuthenticatorForUser;

   type IOnlineIdSystemAuthenticatorStatics_Interface is interface and WinRt.IInspectable_Interface;
   type IOnlineIdSystemAuthenticatorStatics is access all IOnlineIdSystemAuthenticatorStatics_Interface'Class;
   type IOnlineIdSystemAuthenticatorStatics_Ptr is access all IOnlineIdSystemAuthenticatorStatics;

   type IOnlineIdSystemIdentity_Interface is interface and WinRt.IInspectable_Interface;
   type IOnlineIdSystemIdentity is access all IOnlineIdSystemIdentity_Interface'Class;
   type IOnlineIdSystemIdentity_Ptr is access all IOnlineIdSystemIdentity;

   type IOnlineIdSystemTicketResult_Interface is interface and WinRt.IInspectable_Interface;
   type IOnlineIdSystemTicketResult is access all IOnlineIdSystemTicketResult_Interface'Class;
   type IOnlineIdSystemTicketResult_Ptr is access all IOnlineIdSystemTicketResult;

   type IUserIdentity_Interface is interface and WinRt.IInspectable_Interface;
   type IUserIdentity is access all IUserIdentity_Interface'Class;
   type IUserIdentity_Ptr is access all IUserIdentity;

   -----------------------------------------------------------------------------
   -- Enum declarations
   -----------------------------------------------------------------------------

   type CredentialPromptType is (
      PromptIfNeeded_e,
      RetypeCredentials_e,
      DoNotPrompt_e
   );
   for CredentialPromptType use (
      PromptIfNeeded_e => 0,
      RetypeCredentials_e => 1,
      DoNotPrompt_e => 2
   );
   type CredentialPromptType_Ptr is access all CredentialPromptType;

   type OnlineIdSystemTicketStatus is (
      Success_e,
      Error_e,
      ServiceConnectionError_e
   );
   for OnlineIdSystemTicketStatus use (
      Success_e => 0,
      Error_e => 1,
      ServiceConnectionError_e => 2
   );
   type OnlineIdSystemTicketStatus_Ptr is access all OnlineIdSystemTicketStatus;

   -----------------------------------------------------------------------------
   -- Interface declarations
   -----------------------------------------------------------------------------

   -----------------------------------------------------------------------------
   -- type IOnlineIdAuthenticator is interface and WinRt.IInspectable;

      function AuthenticateUserAsync
      (
         this : access IOnlineIdAuthenticator_Interface;
         request : WinRt.Windows.Security.Authentication.OnlineId.IOnlineIdServiceTicketRequest;
         RetVal : access GenericObject
      )
      return WinRt.Hresult is abstract;

      function AuthenticateUserAsync
      (
         this : access IOnlineIdAuthenticator_Interface;
         requests : GenericObject;
         credentialPromptType : WinRt.Windows.Security.Authentication.OnlineId.CredentialPromptType;
         RetVal : access GenericObject
      )
      return WinRt.Hresult is abstract;

      function SignOutUserAsync
      (
         this : access IOnlineIdAuthenticator_Interface;
         RetVal : access WinRt.Windows.Foundation.IAsyncAction
      )
      return WinRt.Hresult is abstract;

      function put_ApplicationId
      (
         this : access IOnlineIdAuthenticator_Interface;
         value : WinRt.Guid
      )
      return WinRt.Hresult is abstract;

      function get_ApplicationId
      (
         this : access IOnlineIdAuthenticator_Interface;
         RetVal : access WinRt.Guid
      )
      return WinRt.Hresult is abstract;

      function get_CanSignOut
      (
         this : access IOnlineIdAuthenticator_Interface;
         RetVal : access WinRt.Boolean
      )
      return WinRt.Hresult is abstract;

      function get_AuthenticatedSafeCustomerId
      (
         this : access IOnlineIdAuthenticator_Interface;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      IID_IOnlineIdAuthenticator : aliased WinRt.IID := (2684614026, 10667, 18455, (184, 132, 215, 81, 109, 173, 24, 185 ));

   -----------------------------------------------------------------------------
   -- type IOnlineIdServiceTicket is interface and WinRt.IInspectable;

      function get_Value
      (
         this : access IOnlineIdServiceTicket_Interface;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      function get_Request
      (
         this : access IOnlineIdServiceTicket_Interface;
         RetVal : access WinRt.Windows.Security.Authentication.OnlineId.IOnlineIdServiceTicketRequest
      )
      return WinRt.Hresult is abstract;

      function get_ErrorCode
      (
         this : access IOnlineIdServiceTicket_Interface;
         RetVal : access WinRt.Int32
      )
      return WinRt.Hresult is abstract;

      IID_IOnlineIdServiceTicket : aliased WinRt.IID := (3378271359, 55169, 19092, (172, 184, 197, 152, 116, 35, 140, 38 ));

   -----------------------------------------------------------------------------
   -- type IOnlineIdServiceTicketRequest is interface and WinRt.IInspectable;

      function get_Service
      (
         this : access IOnlineIdServiceTicketRequest_Interface;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      function get_Policy
      (
         this : access IOnlineIdServiceTicketRequest_Interface;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      IID_IOnlineIdServiceTicketRequest : aliased WinRt.IID := (695485907, 64355, 16693, (137, 9, 78, 53, 76, 6, 20, 102 ));

   -----------------------------------------------------------------------------
   -- type IOnlineIdServiceTicketRequestFactory is interface and WinRt.IInspectable;

      function CreateOnlineIdServiceTicketRequest
      (
         this : access IOnlineIdServiceTicketRequestFactory_Interface;
         service : WinRt.HString;
         policy : WinRt.HString;
         RetVal : access WinRt.Windows.Security.Authentication.OnlineId.IOnlineIdServiceTicketRequest
      )
      return WinRt.Hresult is abstract;

      function CreateOnlineIdServiceTicketRequestAdvanced
      (
         this : access IOnlineIdServiceTicketRequestFactory_Interface;
         service : WinRt.HString;
         RetVal : access WinRt.Windows.Security.Authentication.OnlineId.IOnlineIdServiceTicketRequest
      )
      return WinRt.Hresult is abstract;

      IID_IOnlineIdServiceTicketRequestFactory : aliased WinRt.IID := (3199928840, 40563, 16503, (150, 20, 8, 97, 76, 11, 194, 69 ));

   -----------------------------------------------------------------------------
   -- type IOnlineIdSystemAuthenticatorForUser is interface and WinRt.IInspectable;

      function GetTicketAsync
      (
         this : access IOnlineIdSystemAuthenticatorForUser_Interface;
         request : WinRt.Windows.Security.Authentication.OnlineId.IOnlineIdServiceTicketRequest;
         RetVal : access GenericObject
      )
      return WinRt.Hresult is abstract;

      function put_ApplicationId
      (
         this : access IOnlineIdSystemAuthenticatorForUser_Interface;
         value : WinRt.Guid
      )
      return WinRt.Hresult is abstract;

      function get_ApplicationId
      (
         this : access IOnlineIdSystemAuthenticatorForUser_Interface;
         RetVal : access WinRt.Guid
      )
      return WinRt.Hresult is abstract;

      function get_User
      (
         this : access IOnlineIdSystemAuthenticatorForUser_Interface;
         RetVal : access WinRt.Windows.System.IUser
      )
      return WinRt.Hresult is abstract;

      IID_IOnlineIdSystemAuthenticatorForUser : aliased WinRt.IID := (1469628155, 7652, 16774, (162, 230, 181, 99, 248, 106, 175, 68 ));

   -----------------------------------------------------------------------------
   -- type IOnlineIdSystemAuthenticatorStatics is interface and WinRt.IInspectable;

      function get_Default
      (
         this : access IOnlineIdSystemAuthenticatorStatics_Interface;
         RetVal : access WinRt.Windows.Security.Authentication.OnlineId.IOnlineIdSystemAuthenticatorForUser
      )
      return WinRt.Hresult is abstract;

      function GetForUser
      (
         this : access IOnlineIdSystemAuthenticatorStatics_Interface;
         user : WinRt.Windows.System.IUser;
         RetVal : access WinRt.Windows.Security.Authentication.OnlineId.IOnlineIdSystemAuthenticatorForUser
      )
      return WinRt.Hresult is abstract;

      IID_IOnlineIdSystemAuthenticatorStatics : aliased WinRt.IID := (2231662482, 63028, 16867, (150, 164, 81, 100, 233, 2, 199, 64 ));

   -----------------------------------------------------------------------------
   -- type IOnlineIdSystemIdentity is interface and WinRt.IInspectable;

      function get_Ticket
      (
         this : access IOnlineIdSystemIdentity_Interface;
         RetVal : access WinRt.Windows.Security.Authentication.OnlineId.IOnlineIdServiceTicket
      )
      return WinRt.Hresult is abstract;

      function get_Id
      (
         this : access IOnlineIdSystemIdentity_Interface;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      IID_IOnlineIdSystemIdentity : aliased WinRt.IID := (1950142989, 46794, 17229, (129, 36, 83, 234, 18, 104, 83, 7 ));

   -----------------------------------------------------------------------------
   -- type IOnlineIdSystemTicketResult is interface and WinRt.IInspectable;

      function get_Identity
      (
         this : access IOnlineIdSystemTicketResult_Interface;
         RetVal : access WinRt.Windows.Security.Authentication.OnlineId.IOnlineIdSystemIdentity
      )
      return WinRt.Hresult is abstract;

      function get_Status
      (
         this : access IOnlineIdSystemTicketResult_Interface;
         RetVal : access WinRt.Windows.Security.Authentication.OnlineId.OnlineIdSystemTicketStatus
      )
      return WinRt.Hresult is abstract;

      function get_ExtendedError
      (
         this : access IOnlineIdSystemTicketResult_Interface;
         RetVal : access WinRt.Windows.Foundation.HResult
      )
      return WinRt.Hresult is abstract;

      IID_IOnlineIdSystemTicketResult : aliased WinRt.IID := (3674890232, 45208, 19149, (157, 19, 158, 100, 6, 82, 181, 182 ));

   -----------------------------------------------------------------------------
   -- type IUserIdentity is interface and WinRt.IInspectable;

      function get_Tickets
      (
         this : access IUserIdentity_Interface;
         RetVal : access GenericObject
      )
      return WinRt.Hresult is abstract;

      function get_Id
      (
         this : access IUserIdentity_Interface;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      function get_SafeCustomerId
      (
         this : access IUserIdentity_Interface;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      function get_SignInName
      (
         this : access IUserIdentity_Interface;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      function get_FirstName
      (
         this : access IUserIdentity_Interface;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      function get_LastName
      (
         this : access IUserIdentity_Interface;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      function get_IsBetaAccount
      (
         this : access IUserIdentity_Interface;
         RetVal : access WinRt.Boolean
      )
      return WinRt.Hresult is abstract;

      function get_IsConfirmedPC
      (
         this : access IUserIdentity_Interface;
         RetVal : access WinRt.Boolean
      )
      return WinRt.Hresult is abstract;

      IID_IUserIdentity : aliased WinRt.IID := (558291405, 1858, 19427, (138, 28, 124, 122, 230, 121, 170, 136 ));

end WinRt.Windows.Security.Authentication.OnlineId;
