--------------------------------------------------------------------------------
-- <auto-generated>                                                           --
--     This code was generated by a tool.                                     --
--                                                                            --
--     Changes to this file may cause incorrect behavior and will be lost if  --
--     the code is regenerated.                                               --
-- </auto-generated>                                                          --
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--                                                                            --
--    Copyright(c) 2023 Alexander Gamper, All Rights Reserved.                --
--                                                                            --
--    Ada-WinRT                                                               --
--    Version   : 3.0.0.0                                                     --
--                                                                            --
-- This program is free software: you can redistribute it and / or modify     --
-- it under the terms of the GNU Lesser General Public License as published by--
-- the Free Software Foundation, either version 3 of the License, or          --
-- (at your option) any later version.                                        --
--                                                                            --
-- This program is distributed in the hope that it will be useful,            --
-- but WITHOUT ANY WARRANTY; without even the implied warranty of             --
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the               --
-- GNU Lesser General Public License for more details.                        --
--                                                                            --
-- You should have received a copy of the GNU Lesser General Public License   --
-- along with this program.If not, see http://www.gnu.org/licenses            --
--                                                                            --
--------------------------------------------------------------------------------
with WinRt.Windows.Foundation;
with Ada.Finalization;
--------------------------------------------------------------------------------
package WinRt.Windows.UI.WindowManagement.Preview is

   pragma PreElaborate;

   -----------------------------------------------------------------------------
   -- Forward Interface declarations
   -----------------------------------------------------------------------------

   type IWindowManagementPreview_Interface is interface and WinRt.IInspectable_Interface;
   type IWindowManagementPreview is access IWindowManagementPreview_Interface'Class;
   type IWindowManagementPreview_Ptr is access all IWindowManagementPreview;

   type IWindowManagementPreviewStatics_Interface is interface and WinRt.IInspectable_Interface;
   type IWindowManagementPreviewStatics is access IWindowManagementPreviewStatics_Interface'Class;

   -----------------------------------------------------------------------------
   -- Class declarations
   -----------------------------------------------------------------------------

   type WindowManagementPreview is new Ada.Finalization.Limited_Controlled with
      record
         m_IWindowManagementPreview : access Windows.UI.WindowManagement.Preview.IWindowManagementPreview;
      end record;
   type WindowManagementPreview_Ptr is access all WindowManagementPreview;

   -----------------------------------------------------------------------------
   -- Interface declarations
   -----------------------------------------------------------------------------

   -----------------------------------------------------------------------------
   -- type IWindowManagementPreview is interface and WinRt.IInspectable;

      IID_IWindowManagementPreview : aliased WinRt.IID := (1324702477, 22045, 20796, (166, 124, 44, 2, 182, 156, 239, 65 ));

   -----------------------------------------------------------------------------
   -- type IWindowManagementPreviewStatics is interface and WinRt.IInspectable;

      function SetPreferredMinSize
      (
         this : access IWindowManagementPreviewStatics_Interface;
         window : Windows.UI.WindowManagement.IAppWindow;
         preferredFrameMinSize : Windows.Foundation.Size
      )
      return WinRt.Hresult is abstract;

      IID_IWindowManagementPreviewStatics : aliased WinRt.IID := (261563846, 49156, 23075, (143, 210, 141, 9, 44, 226, 112, 74 ));

   -----------------------------------------------------------------------------
   -- Class method declarations
   -----------------------------------------------------------------------------

   -----------------------------------------------------------------------------
   -- RuntimeClass Initialization/Finalization for WindowManagementPreview

   overriding procedure Initialize (this : in out WindowManagementPreview);
   overriding procedure Finalize (this : in out WindowManagementPreview);

   -----------------------------------------------------------------------------
   -- Static Interfaces for WindowManagementPreview

   procedure SetPreferredMinSize
   (
      window : Windows.UI.WindowManagement.AppWindow'Class;
      preferredFrameMinSize : Windows.Foundation.Size
   );

   -----------------------------------------------------------------------------
   -- Implemented Interfaces for WindowManagementPreview

end;
