--------------------------------------------------------------------------------
-- <auto-generated>                                                           --
--     This code was generated by a tool.                                     --
--                                                                            --
--     Changes to this file may cause incorrect behavior and will be lost if  --
--     the code is regenerated.                                               --
-- </auto-generated>                                                          --
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--                                                                            --
--    Copyright(c) 2023 Alexander Gamper, All Rights Reserved.                --
--                                                                            --
--    Ada-WinRT                                                               --
--    Version   : 3.0.0.0                                                     --
--                                                                            --
-- This program is free software: you can redistribute it and / or modify     --
-- it under the terms of the GNU Lesser General Public License as published by--
-- the Free Software Foundation, either version 3 of the License, or          --
-- (at your option) any later version.                                        --
--                                                                            --
-- This program is distributed in the hope that it will be useful,            --
-- but WITHOUT ANY WARRANTY; without even the implied warranty of             --
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the               --
-- GNU Lesser General Public License for more details.                        --
--                                                                            --
-- You should have received a copy of the GNU Lesser General Public License   --
-- along with this program.If not, see http://www.gnu.org/licenses            --
--                                                                            --
--------------------------------------------------------------------------------
limited with WinRt.Windows.ApplicationModel.AppService;
with WinRt.Windows.Foundation;
with WinRt.Windows.Foundation.Collections;
limited with WinRt.Windows.Networking;
limited with WinRt.Windows.Security.Credentials;
with Ada.Finalization;
--------------------------------------------------------------------------------
package WinRt.Windows.System.RemoteSystems is

   pragma PreElaborate;

   -----------------------------------------------------------------------------
   -- Forward Interface declarations
   -----------------------------------------------------------------------------

   type IKnownRemoteSystemCapabilitiesStatics_Interface is interface and WinRt.IInspectable_Interface;
   type IKnownRemoteSystemCapabilitiesStatics is access all IKnownRemoteSystemCapabilitiesStatics_Interface'Class;
   type IKnownRemoteSystemCapabilitiesStatics_Ptr is access all IKnownRemoteSystemCapabilitiesStatics;

   type IRemoteSystem_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystem is access all IRemoteSystem_Interface'Class;
   type IRemoteSystem_Ptr is access all IRemoteSystem;

   type IRemoteSystem2_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystem2 is access all IRemoteSystem2_Interface'Class;
   type IRemoteSystem2_Ptr is access all IRemoteSystem2;

   type IRemoteSystem3_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystem3 is access all IRemoteSystem3_Interface'Class;
   type IRemoteSystem3_Ptr is access all IRemoteSystem3;

   type IRemoteSystem4_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystem4 is access all IRemoteSystem4_Interface'Class;
   type IRemoteSystem4_Ptr is access all IRemoteSystem4;

   type IRemoteSystem5_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystem5 is access all IRemoteSystem5_Interface'Class;
   type IRemoteSystem5_Ptr is access all IRemoteSystem5;

   type IRemoteSystem6_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystem6 is access all IRemoteSystem6_Interface'Class;
   type IRemoteSystem6_Ptr is access all IRemoteSystem6;

   type IRemoteSystemAddedEventArgs_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemAddedEventArgs is access all IRemoteSystemAddedEventArgs_Interface'Class;
   type IRemoteSystemAddedEventArgs_Ptr is access all IRemoteSystemAddedEventArgs;

   type IRemoteSystemApp_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemApp is access all IRemoteSystemApp_Interface'Class;
   type IRemoteSystemApp_Ptr is access all IRemoteSystemApp;

   type IRemoteSystemApp2_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemApp2 is access all IRemoteSystemApp2_Interface'Class;
   type IRemoteSystemApp2_Ptr is access all IRemoteSystemApp2;

   type IRemoteSystemAppRegistration_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemAppRegistration is access all IRemoteSystemAppRegistration_Interface'Class;
   type IRemoteSystemAppRegistration_Ptr is access all IRemoteSystemAppRegistration;

   type IRemoteSystemAppRegistrationStatics_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemAppRegistrationStatics is access all IRemoteSystemAppRegistrationStatics_Interface'Class;
   type IRemoteSystemAppRegistrationStatics_Ptr is access all IRemoteSystemAppRegistrationStatics;

   type IRemoteSystemAuthorizationKindFilter_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemAuthorizationKindFilter is access all IRemoteSystemAuthorizationKindFilter_Interface'Class;
   type IRemoteSystemAuthorizationKindFilter_Ptr is access all IRemoteSystemAuthorizationKindFilter;

   type IRemoteSystemAuthorizationKindFilterFactory_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemAuthorizationKindFilterFactory is access all IRemoteSystemAuthorizationKindFilterFactory_Interface'Class;
   type IRemoteSystemAuthorizationKindFilterFactory_Ptr is access all IRemoteSystemAuthorizationKindFilterFactory;

   type IRemoteSystemConnectionInfo_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemConnectionInfo is access all IRemoteSystemConnectionInfo_Interface'Class;
   type IRemoteSystemConnectionInfo_Ptr is access all IRemoteSystemConnectionInfo;

   type IRemoteSystemConnectionInfoStatics_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemConnectionInfoStatics is access all IRemoteSystemConnectionInfoStatics_Interface'Class;
   type IRemoteSystemConnectionInfoStatics_Ptr is access all IRemoteSystemConnectionInfoStatics;

   type IRemoteSystemConnectionRequest_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemConnectionRequest is access all IRemoteSystemConnectionRequest_Interface'Class;
   type IRemoteSystemConnectionRequest_Ptr is access all IRemoteSystemConnectionRequest;

   type IRemoteSystemConnectionRequest2_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemConnectionRequest2 is access all IRemoteSystemConnectionRequest2_Interface'Class;
   type IRemoteSystemConnectionRequest2_Ptr is access all IRemoteSystemConnectionRequest2;

   type IRemoteSystemConnectionRequest3_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemConnectionRequest3 is access all IRemoteSystemConnectionRequest3_Interface'Class;
   type IRemoteSystemConnectionRequest3_Ptr is access all IRemoteSystemConnectionRequest3;

   type IRemoteSystemConnectionRequestFactory_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemConnectionRequestFactory is access all IRemoteSystemConnectionRequestFactory_Interface'Class;
   type IRemoteSystemConnectionRequestFactory_Ptr is access all IRemoteSystemConnectionRequestFactory;

   type IRemoteSystemConnectionRequestStatics_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemConnectionRequestStatics is access all IRemoteSystemConnectionRequestStatics_Interface'Class;
   type IRemoteSystemConnectionRequestStatics_Ptr is access all IRemoteSystemConnectionRequestStatics;

   type IRemoteSystemConnectionRequestStatics2_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemConnectionRequestStatics2 is access all IRemoteSystemConnectionRequestStatics2_Interface'Class;
   type IRemoteSystemConnectionRequestStatics2_Ptr is access all IRemoteSystemConnectionRequestStatics2;

   type IRemoteSystemDiscoveryTypeFilter_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemDiscoveryTypeFilter is access all IRemoteSystemDiscoveryTypeFilter_Interface'Class;
   type IRemoteSystemDiscoveryTypeFilter_Ptr is access all IRemoteSystemDiscoveryTypeFilter;

   type IRemoteSystemDiscoveryTypeFilterFactory_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemDiscoveryTypeFilterFactory is access all IRemoteSystemDiscoveryTypeFilterFactory_Interface'Class;
   type IRemoteSystemDiscoveryTypeFilterFactory_Ptr is access all IRemoteSystemDiscoveryTypeFilterFactory;

   type IRemoteSystemEnumerationCompletedEventArgs_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemEnumerationCompletedEventArgs is access all IRemoteSystemEnumerationCompletedEventArgs_Interface'Class;
   type IRemoteSystemEnumerationCompletedEventArgs_Ptr is access all IRemoteSystemEnumerationCompletedEventArgs;

   type IRemoteSystemFilter_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemFilter is access all IRemoteSystemFilter_Interface'Class;
   type IRemoteSystemFilter_Ptr is access all IRemoteSystemFilter;

   type IRemoteSystemKindFilter_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemKindFilter is access all IRemoteSystemKindFilter_Interface'Class;
   type IRemoteSystemKindFilter_Ptr is access all IRemoteSystemKindFilter;

   type IRemoteSystemKindFilterFactory_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemKindFilterFactory is access all IRemoteSystemKindFilterFactory_Interface'Class;
   type IRemoteSystemKindFilterFactory_Ptr is access all IRemoteSystemKindFilterFactory;

   type IRemoteSystemKindStatics_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemKindStatics is access all IRemoteSystemKindStatics_Interface'Class;
   type IRemoteSystemKindStatics_Ptr is access all IRemoteSystemKindStatics;

   type IRemoteSystemKindStatics2_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemKindStatics2 is access all IRemoteSystemKindStatics2_Interface'Class;
   type IRemoteSystemKindStatics2_Ptr is access all IRemoteSystemKindStatics2;

   type IRemoteSystemRemovedEventArgs_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemRemovedEventArgs is access all IRemoteSystemRemovedEventArgs_Interface'Class;
   type IRemoteSystemRemovedEventArgs_Ptr is access all IRemoteSystemRemovedEventArgs;

   type IRemoteSystemSession_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemSession is access all IRemoteSystemSession_Interface'Class;
   type IRemoteSystemSession_Ptr is access all IRemoteSystemSession;

   type IRemoteSystemSessionAddedEventArgs_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemSessionAddedEventArgs is access all IRemoteSystemSessionAddedEventArgs_Interface'Class;
   type IRemoteSystemSessionAddedEventArgs_Ptr is access all IRemoteSystemSessionAddedEventArgs;

   type IRemoteSystemSessionController_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemSessionController is access all IRemoteSystemSessionController_Interface'Class;
   type IRemoteSystemSessionController_Ptr is access all IRemoteSystemSessionController;

   type IRemoteSystemSessionControllerFactory_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemSessionControllerFactory is access all IRemoteSystemSessionControllerFactory_Interface'Class;
   type IRemoteSystemSessionControllerFactory_Ptr is access all IRemoteSystemSessionControllerFactory;

   type IRemoteSystemSessionCreationResult_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemSessionCreationResult is access all IRemoteSystemSessionCreationResult_Interface'Class;
   type IRemoteSystemSessionCreationResult_Ptr is access all IRemoteSystemSessionCreationResult;

   type IRemoteSystemSessionDisconnectedEventArgs_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemSessionDisconnectedEventArgs is access all IRemoteSystemSessionDisconnectedEventArgs_Interface'Class;
   type IRemoteSystemSessionDisconnectedEventArgs_Ptr is access all IRemoteSystemSessionDisconnectedEventArgs;

   type IRemoteSystemSessionInfo_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemSessionInfo is access all IRemoteSystemSessionInfo_Interface'Class;
   type IRemoteSystemSessionInfo_Ptr is access all IRemoteSystemSessionInfo;

   type IRemoteSystemSessionInvitation_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemSessionInvitation is access all IRemoteSystemSessionInvitation_Interface'Class;
   type IRemoteSystemSessionInvitation_Ptr is access all IRemoteSystemSessionInvitation;

   type IRemoteSystemSessionInvitationListener_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemSessionInvitationListener is access all IRemoteSystemSessionInvitationListener_Interface'Class;
   type IRemoteSystemSessionInvitationListener_Ptr is access all IRemoteSystemSessionInvitationListener;

   type IRemoteSystemSessionInvitationReceivedEventArgs_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemSessionInvitationReceivedEventArgs is access all IRemoteSystemSessionInvitationReceivedEventArgs_Interface'Class;
   type IRemoteSystemSessionInvitationReceivedEventArgs_Ptr is access all IRemoteSystemSessionInvitationReceivedEventArgs;

   type IRemoteSystemSessionJoinRequest_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemSessionJoinRequest is access all IRemoteSystemSessionJoinRequest_Interface'Class;
   type IRemoteSystemSessionJoinRequest_Ptr is access all IRemoteSystemSessionJoinRequest;

   type IRemoteSystemSessionJoinRequestedEventArgs_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemSessionJoinRequestedEventArgs is access all IRemoteSystemSessionJoinRequestedEventArgs_Interface'Class;
   type IRemoteSystemSessionJoinRequestedEventArgs_Ptr is access all IRemoteSystemSessionJoinRequestedEventArgs;

   type IRemoteSystemSessionJoinResult_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemSessionJoinResult is access all IRemoteSystemSessionJoinResult_Interface'Class;
   type IRemoteSystemSessionJoinResult_Ptr is access all IRemoteSystemSessionJoinResult;

   type IRemoteSystemSessionMessageChannel_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemSessionMessageChannel is access all IRemoteSystemSessionMessageChannel_Interface'Class;
   type IRemoteSystemSessionMessageChannel_Ptr is access all IRemoteSystemSessionMessageChannel;

   type IRemoteSystemSessionMessageChannelFactory_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemSessionMessageChannelFactory is access all IRemoteSystemSessionMessageChannelFactory_Interface'Class;
   type IRemoteSystemSessionMessageChannelFactory_Ptr is access all IRemoteSystemSessionMessageChannelFactory;

   type IRemoteSystemSessionOptions_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemSessionOptions is access all IRemoteSystemSessionOptions_Interface'Class;
   type IRemoteSystemSessionOptions_Ptr is access all IRemoteSystemSessionOptions;

   type IRemoteSystemSessionParticipant_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemSessionParticipant is access all IRemoteSystemSessionParticipant_Interface'Class;
   type IRemoteSystemSessionParticipant_Ptr is access all IRemoteSystemSessionParticipant;

   type IRemoteSystemSessionParticipantAddedEventArgs_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemSessionParticipantAddedEventArgs is access all IRemoteSystemSessionParticipantAddedEventArgs_Interface'Class;
   type IRemoteSystemSessionParticipantAddedEventArgs_Ptr is access all IRemoteSystemSessionParticipantAddedEventArgs;

   type IRemoteSystemSessionParticipantRemovedEventArgs_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemSessionParticipantRemovedEventArgs is access all IRemoteSystemSessionParticipantRemovedEventArgs_Interface'Class;
   type IRemoteSystemSessionParticipantRemovedEventArgs_Ptr is access all IRemoteSystemSessionParticipantRemovedEventArgs;

   type IRemoteSystemSessionParticipantWatcher_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemSessionParticipantWatcher is access all IRemoteSystemSessionParticipantWatcher_Interface'Class;
   type IRemoteSystemSessionParticipantWatcher_Ptr is access all IRemoteSystemSessionParticipantWatcher;

   type IRemoteSystemSessionRemovedEventArgs_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemSessionRemovedEventArgs is access all IRemoteSystemSessionRemovedEventArgs_Interface'Class;
   type IRemoteSystemSessionRemovedEventArgs_Ptr is access all IRemoteSystemSessionRemovedEventArgs;

   type IRemoteSystemSessionStatics_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemSessionStatics is access all IRemoteSystemSessionStatics_Interface'Class;
   type IRemoteSystemSessionStatics_Ptr is access all IRemoteSystemSessionStatics;

   type IRemoteSystemSessionUpdatedEventArgs_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemSessionUpdatedEventArgs is access all IRemoteSystemSessionUpdatedEventArgs_Interface'Class;
   type IRemoteSystemSessionUpdatedEventArgs_Ptr is access all IRemoteSystemSessionUpdatedEventArgs;

   type IRemoteSystemSessionValueSetReceivedEventArgs_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemSessionValueSetReceivedEventArgs is access all IRemoteSystemSessionValueSetReceivedEventArgs_Interface'Class;
   type IRemoteSystemSessionValueSetReceivedEventArgs_Ptr is access all IRemoteSystemSessionValueSetReceivedEventArgs;

   type IRemoteSystemSessionWatcher_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemSessionWatcher is access all IRemoteSystemSessionWatcher_Interface'Class;
   type IRemoteSystemSessionWatcher_Ptr is access all IRemoteSystemSessionWatcher;

   type IRemoteSystemStatics_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemStatics is access all IRemoteSystemStatics_Interface'Class;
   type IRemoteSystemStatics_Ptr is access all IRemoteSystemStatics;

   type IRemoteSystemStatics2_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemStatics2 is access all IRemoteSystemStatics2_Interface'Class;
   type IRemoteSystemStatics2_Ptr is access all IRemoteSystemStatics2;

   type IRemoteSystemStatics3_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemStatics3 is access all IRemoteSystemStatics3_Interface'Class;
   type IRemoteSystemStatics3_Ptr is access all IRemoteSystemStatics3;

   type IRemoteSystemStatusTypeFilter_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemStatusTypeFilter is access all IRemoteSystemStatusTypeFilter_Interface'Class;
   type IRemoteSystemStatusTypeFilter_Ptr is access all IRemoteSystemStatusTypeFilter;

   type IRemoteSystemStatusTypeFilterFactory_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemStatusTypeFilterFactory is access all IRemoteSystemStatusTypeFilterFactory_Interface'Class;
   type IRemoteSystemStatusTypeFilterFactory_Ptr is access all IRemoteSystemStatusTypeFilterFactory;

   type IRemoteSystemUpdatedEventArgs_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemUpdatedEventArgs is access all IRemoteSystemUpdatedEventArgs_Interface'Class;
   type IRemoteSystemUpdatedEventArgs_Ptr is access all IRemoteSystemUpdatedEventArgs;

   type IRemoteSystemWatcher_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemWatcher is access all IRemoteSystemWatcher_Interface'Class;
   type IRemoteSystemWatcher_Ptr is access all IRemoteSystemWatcher;

   type IRemoteSystemWatcher2_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemWatcher2 is access all IRemoteSystemWatcher2_Interface'Class;
   type IRemoteSystemWatcher2_Ptr is access all IRemoteSystemWatcher2;

   type IRemoteSystemWatcher3_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemWatcher3 is access all IRemoteSystemWatcher3_Interface'Class;
   type IRemoteSystemWatcher3_Ptr is access all IRemoteSystemWatcher3;

   type IRemoteSystemWatcherErrorOccurredEventArgs_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemWatcherErrorOccurredEventArgs is access all IRemoteSystemWatcherErrorOccurredEventArgs_Interface'Class;
   type IRemoteSystemWatcherErrorOccurredEventArgs_Ptr is access all IRemoteSystemWatcherErrorOccurredEventArgs;

   type IRemoteSystemWebAccountFilter_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemWebAccountFilter is access all IRemoteSystemWebAccountFilter_Interface'Class;
   type IRemoteSystemWebAccountFilter_Ptr is access all IRemoteSystemWebAccountFilter;

   type IRemoteSystemWebAccountFilterFactory_Interface is interface and WinRt.IInspectable_Interface;
   type IRemoteSystemWebAccountFilterFactory is access all IRemoteSystemWebAccountFilterFactory_Interface'Class;
   type IRemoteSystemWebAccountFilterFactory_Ptr is access all IRemoteSystemWebAccountFilterFactory;

   -----------------------------------------------------------------------------
   -- Enum declarations
   -----------------------------------------------------------------------------

   type RemoteSystemAccessStatus is (
      Unspecified_e,
      Allowed_e,
      DeniedByUser_e,
      DeniedBySystem_e
   );
   for RemoteSystemAccessStatus use (
      Unspecified_e => 0,
      Allowed_e => 1,
      DeniedByUser_e => 2,
      DeniedBySystem_e => 3
   );
   type RemoteSystemAccessStatus_Ptr is access all RemoteSystemAccessStatus;

   type RemoteSystemAuthorizationKind is (
      SameUser_e,
      Anonymous_e,
      SameFamily_e
   );
   for RemoteSystemAuthorizationKind use (
      SameUser_e => 0,
      Anonymous_e => 1,
      SameFamily_e => 2
   );
   type RemoteSystemAuthorizationKind_Ptr is access all RemoteSystemAuthorizationKind;

   type RemoteSystemDiscoveryType is (
      Any_e,
      Proximal_e,
      Cloud_e,
      SpatiallyProximal_e
   );
   for RemoteSystemDiscoveryType use (
      Any_e => 0,
      Proximal_e => 1,
      Cloud_e => 2,
      SpatiallyProximal_e => 3
   );
   type RemoteSystemDiscoveryType_Ptr is access all RemoteSystemDiscoveryType;

   type RemoteSystemPlatform is (
      Unknown_e,
      Windows_e,
      Android_e,
      Ios_e,
      Linux_e
   );
   for RemoteSystemPlatform use (
      Unknown_e => 0,
      Windows_e => 1,
      Android_e => 2,
      Ios_e => 3,
      Linux_e => 4
   );
   type RemoteSystemPlatform_Ptr is access all RemoteSystemPlatform;

   type RemoteSystemSessionCreationStatus is (
      Success_e,
      SessionLimitsExceeded_e,
      OperationAborted_e
   );
   for RemoteSystemSessionCreationStatus use (
      Success_e => 0,
      SessionLimitsExceeded_e => 1,
      OperationAborted_e => 2
   );
   type RemoteSystemSessionCreationStatus_Ptr is access all RemoteSystemSessionCreationStatus;

   type RemoteSystemSessionDisconnectedReason is (
      SessionUnavailable_e,
      RemovedByController_e,
      SessionClosed_e
   );
   for RemoteSystemSessionDisconnectedReason use (
      SessionUnavailable_e => 0,
      RemovedByController_e => 1,
      SessionClosed_e => 2
   );
   type RemoteSystemSessionDisconnectedReason_Ptr is access all RemoteSystemSessionDisconnectedReason;

   type RemoteSystemSessionJoinStatus is (
      Success_e,
      SessionLimitsExceeded_e,
      OperationAborted_e,
      SessionUnavailable_e,
      RejectedByController_e
   );
   for RemoteSystemSessionJoinStatus use (
      Success_e => 0,
      SessionLimitsExceeded_e => 1,
      OperationAborted_e => 2,
      SessionUnavailable_e => 3,
      RejectedByController_e => 4
   );
   type RemoteSystemSessionJoinStatus_Ptr is access all RemoteSystemSessionJoinStatus;

   type RemoteSystemSessionMessageChannelReliability is (
      Reliable_e,
      Unreliable_e
   );
   for RemoteSystemSessionMessageChannelReliability use (
      Reliable_e => 0,
      Unreliable_e => 1
   );
   type RemoteSystemSessionMessageChannelReliability_Ptr is access all RemoteSystemSessionMessageChannelReliability;

   type RemoteSystemSessionParticipantWatcherStatus is (
      Created_e,
      Started_e,
      EnumerationCompleted_e,
      Stopping_e,
      Stopped_e,
      Aborted_e
   );
   for RemoteSystemSessionParticipantWatcherStatus use (
      Created_e => 0,
      Started_e => 1,
      EnumerationCompleted_e => 2,
      Stopping_e => 3,
      Stopped_e => 4,
      Aborted_e => 5
   );
   type RemoteSystemSessionParticipantWatcherStatus_Ptr is access all RemoteSystemSessionParticipantWatcherStatus;

   type RemoteSystemSessionWatcherStatus is (
      Created_e,
      Started_e,
      EnumerationCompleted_e,
      Stopping_e,
      Stopped_e,
      Aborted_e
   );
   for RemoteSystemSessionWatcherStatus use (
      Created_e => 0,
      Started_e => 1,
      EnumerationCompleted_e => 2,
      Stopping_e => 3,
      Stopped_e => 4,
      Aborted_e => 5
   );
   type RemoteSystemSessionWatcherStatus_Ptr is access all RemoteSystemSessionWatcherStatus;

   type RemoteSystemStatus is (
      Unavailable_e,
      DiscoveringAvailability_e,
      Available_e,
      Unknown_e
   );
   for RemoteSystemStatus use (
      Unavailable_e => 0,
      DiscoveringAvailability_e => 1,
      Available_e => 2,
      Unknown_e => 3
   );
   type RemoteSystemStatus_Ptr is access all RemoteSystemStatus;

   type RemoteSystemStatusType is (
      Any_e,
      Available_e
   );
   for RemoteSystemStatusType use (
      Any_e => 0,
      Available_e => 1
   );
   type RemoteSystemStatusType_Ptr is access all RemoteSystemStatusType;

   type RemoteSystemWatcherError is (
      Unknown_e,
      InternetNotAvailable_e,
      AuthenticationError_e
   );
   for RemoteSystemWatcherError use (
      Unknown_e => 0,
      InternetNotAvailable_e => 1,
      AuthenticationError_e => 2
   );
   type RemoteSystemWatcherError_Ptr is access all RemoteSystemWatcherError;

   -----------------------------------------------------------------------------
   -- Interface declarations
   -----------------------------------------------------------------------------

   -----------------------------------------------------------------------------
   -- type IKnownRemoteSystemCapabilitiesStatics is interface and WinRt.IInspectable;

      function get_AppService
      (
         this : access IKnownRemoteSystemCapabilitiesStatics_Interface;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      function get_LaunchUri
      (
         this : access IKnownRemoteSystemCapabilitiesStatics_Interface;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      function get_RemoteSession
      (
         this : access IKnownRemoteSystemCapabilitiesStatics_Interface;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      function get_SpatialEntity
      (
         this : access IKnownRemoteSystemCapabilitiesStatics_Interface;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      IID_IKnownRemoteSystemCapabilitiesStatics : aliased WinRt.IID := (2164843392, 32650, 17636, (146, 205, 3, 182, 70, 155, 148, 163 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystem is interface and WinRt.IInspectable;

      function get_DisplayName
      (
         this : access IRemoteSystem_Interface;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      function get_Id
      (
         this : access IRemoteSystem_Interface;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      function get_Kind
      (
         this : access IRemoteSystem_Interface;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      function get_Status
      (
         this : access IRemoteSystem_Interface;
         RetVal : access WinRt.Windows.System.RemoteSystems.RemoteSystemStatus
      )
      return WinRt.Hresult is abstract;

      function get_IsAvailableByProximity
      (
         this : access IRemoteSystem_Interface;
         RetVal : access WinRt.Boolean
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystem : aliased WinRt.IID := (3981981901, 7696, 19084, (180, 166, 78, 95, 214, 249, 119, 33 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystem2 is interface and WinRt.IInspectable;

      function get_IsAvailableBySpatialProximity
      (
         this : access IRemoteSystem2_Interface;
         RetVal : access WinRt.Boolean
      )
      return WinRt.Hresult is abstract;

      function GetCapabilitySupportedAsync
      (
         this : access IRemoteSystem2_Interface;
         capabilityName : WinRt.HString;
         RetVal : access GenericObject
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystem2 : aliased WinRt.IID := (165668076, 64395, 18952, (167, 88, 104, 118, 67, 93, 118, 158 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystem3 is interface and WinRt.IInspectable;

      function get_ManufacturerDisplayName
      (
         this : access IRemoteSystem3_Interface;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      function get_ModelDisplayName
      (
         this : access IRemoteSystem3_Interface;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystem3 : aliased WinRt.IID := (1924445333, 47046, 16574, (131, 27, 115, 86, 47, 18, 255, 168 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystem4 is interface and WinRt.IInspectable;

      function get_Platform
      (
         this : access IRemoteSystem4_Interface;
         RetVal : access WinRt.Windows.System.RemoteSystems.RemoteSystemPlatform
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystem4 : aliased WinRt.IID := (4049928165, 47495, 19621, (153, 38, 250, 4, 56, 190, 98, 115 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystem5 is interface and WinRt.IInspectable;

      function get_Apps
      (
         this : access IRemoteSystem5_Interface;
         RetVal : access GenericObject
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystem5 : aliased WinRt.IID := (3945453347, 58850, 19170, (167, 167, 161, 9, 122, 9, 142, 144 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystem6 is interface and WinRt.IInspectable;

      function get_User
      (
         this : access IRemoteSystem6_Interface;
         RetVal : access WinRt.Windows.System.IUser
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystem6 : aliased WinRt.IID := (3570248002, 49191, 21310, (147, 132, 58, 25, 180, 247, 238, 243 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemAddedEventArgs is interface and WinRt.IInspectable;

      function get_RemoteSystem
      (
         this : access IRemoteSystemAddedEventArgs_Interface;
         RetVal : access WinRt.Windows.System.RemoteSystems.IRemoteSystem
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemAddedEventArgs : aliased WinRt.IID := (2402899471, 58676, 18071, (136, 54, 122, 190, 161, 81, 81, 110 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemApp is interface and WinRt.IInspectable;

      function get_Id
      (
         this : access IRemoteSystemApp_Interface;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      function get_DisplayName
      (
         this : access IRemoteSystemApp_Interface;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      function get_IsAvailableByProximity
      (
         this : access IRemoteSystemApp_Interface;
         RetVal : access WinRt.Boolean
      )
      return WinRt.Hresult is abstract;

      function get_IsAvailableBySpatialProximity
      (
         this : access IRemoteSystemApp_Interface;
         RetVal : access WinRt.Boolean
      )
      return WinRt.Hresult is abstract;

      function get_Attributes
      (
         this : access IRemoteSystemApp_Interface;
         RetVal : access GenericObject
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemApp : aliased WinRt.IID := (2162539709, 54605, 16817, (155, 22, 104, 16, 168, 113, 237, 79 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemApp2 is interface and WinRt.IInspectable;

      function get_User
      (
         this : access IRemoteSystemApp2_Interface;
         RetVal : access WinRt.Windows.System.IUser
      )
      return WinRt.Hresult is abstract;

      function get_ConnectionToken
      (
         this : access IRemoteSystemApp2_Interface;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemApp2 : aliased WinRt.IID := (1667874581, 2710, 22394, (143, 246, 195, 89, 4, 223, 168, 243 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemAppRegistration is interface and WinRt.IInspectable;

      function get_User
      (
         this : access IRemoteSystemAppRegistration_Interface;
         RetVal : access WinRt.Windows.System.IUser
      )
      return WinRt.Hresult is abstract;

      function get_Attributes
      (
         this : access IRemoteSystemAppRegistration_Interface;
         RetVal : access GenericObject
      )
      return WinRt.Hresult is abstract;

      function SaveAsync
      (
         this : access IRemoteSystemAppRegistration_Interface;
         RetVal : access GenericObject
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemAppRegistration : aliased WinRt.IID := (3027847093, 28725, 19034, (184, 223, 150, 45, 143, 132, 49, 244 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemAppRegistrationStatics is interface and WinRt.IInspectable;

      function GetDefault
      (
         this : access IRemoteSystemAppRegistrationStatics_Interface;
         RetVal : access WinRt.Windows.System.RemoteSystems.IRemoteSystemAppRegistration
      )
      return WinRt.Hresult is abstract;

      function GetForUser
      (
         this : access IRemoteSystemAppRegistrationStatics_Interface;
         user : WinRt.Windows.System.IUser;
         RetVal : access WinRt.Windows.System.RemoteSystems.IRemoteSystemAppRegistration
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemAppRegistrationStatics : aliased WinRt.IID := (28940352, 53202, 17727, (174, 37, 194, 83, 159, 8, 106, 253 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemAuthorizationKindFilter is interface and WinRt.IInspectable;

      function get_RemoteSystemAuthorizationKind
      (
         this : access IRemoteSystemAuthorizationKindFilter_Interface;
         RetVal : access WinRt.Windows.System.RemoteSystems.RemoteSystemAuthorizationKind
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemAuthorizationKindFilter : aliased WinRt.IID := (1796071054, 1232, 16628, (162, 127, 194, 172, 187, 214, 183, 52 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemAuthorizationKindFilterFactory is interface and WinRt.IInspectable;

      function Create
      (
         this : access IRemoteSystemAuthorizationKindFilterFactory_Interface;
         remoteSystemAuthorizationKind : WinRt.Windows.System.RemoteSystems.RemoteSystemAuthorizationKind;
         RetVal : access WinRt.Windows.System.RemoteSystems.IRemoteSystemAuthorizationKindFilter
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemAuthorizationKindFilterFactory : aliased WinRt.IID := (2909134669, 46698, 17828, (129, 119, 140, 174, 215, 93, 158, 90 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemConnectionInfo is interface and WinRt.IInspectable;

      function get_IsProximal
      (
         this : access IRemoteSystemConnectionInfo_Interface;
         RetVal : access WinRt.Boolean
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemConnectionInfo : aliased WinRt.IID := (589794243, 3337, 21195, (156, 106, 238, 210, 148, 11, 238, 67 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemConnectionInfoStatics is interface and WinRt.IInspectable;

      function TryCreateFromAppServiceConnection
      (
         this : access IRemoteSystemConnectionInfoStatics_Interface;
         connection : WinRt.Windows.ApplicationModel.AppService.IAppServiceConnection;
         RetVal : access WinRt.Windows.System.RemoteSystems.IRemoteSystemConnectionInfo
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemConnectionInfoStatics : aliased WinRt.IID := (2894274093, 26309, 22231, (164, 206, 112, 93, 148, 146, 90, 214 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemConnectionRequest is interface and WinRt.IInspectable;

      function get_RemoteSystem
      (
         this : access IRemoteSystemConnectionRequest_Interface;
         RetVal : access WinRt.Windows.System.RemoteSystems.IRemoteSystem
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemConnectionRequest : aliased WinRt.IID := (2230141188, 36190, 19826, (130, 56, 118, 33, 87, 108, 122, 103 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemConnectionRequest2 is interface and WinRt.IInspectable;

      function get_RemoteSystemApp
      (
         this : access IRemoteSystemConnectionRequest2_Interface;
         RetVal : access WinRt.Windows.System.RemoteSystems.IRemoteSystemApp
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemConnectionRequest2 : aliased WinRt.IID := (316632431, 49148, 18490, (138, 190, 211, 74, 108, 25, 249, 43 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemConnectionRequest3 is interface and WinRt.IInspectable;

      function get_ConnectionToken
      (
         this : access IRemoteSystemConnectionRequest3_Interface;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemConnectionRequest3 : aliased WinRt.IID := (3733373927, 51660, 23120, (184, 217, 186, 123, 52, 187, 141, 14 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemConnectionRequestFactory is interface and WinRt.IInspectable;

      function Create
      (
         this : access IRemoteSystemConnectionRequestFactory_Interface;
         remoteSystem : WinRt.Windows.System.RemoteSystems.IRemoteSystem;
         RetVal : access WinRt.Windows.System.RemoteSystems.IRemoteSystemConnectionRequest
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemConnectionRequestFactory : aliased WinRt.IID := (2852784672, 47851, 17781, (181, 48, 129, 11, 185, 120, 99, 52 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemConnectionRequestStatics is interface and WinRt.IInspectable;

      function CreateForApp
      (
         this : access IRemoteSystemConnectionRequestStatics_Interface;
         remoteSystemApp : WinRt.Windows.System.RemoteSystems.IRemoteSystemApp;
         RetVal : access WinRt.Windows.System.RemoteSystems.IRemoteSystemConnectionRequest
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemConnectionRequestStatics : aliased WinRt.IID := (2261390397, 33300, 16988, (137, 50, 219, 73, 3, 45, 19, 6 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemConnectionRequestStatics2 is interface and WinRt.IInspectable;

      function CreateFromConnectionToken
      (
         this : access IRemoteSystemConnectionRequestStatics2_Interface;
         connectionToken : WinRt.HString;
         RetVal : access WinRt.Windows.System.RemoteSystems.IRemoteSystemConnectionRequest
      )
      return WinRt.Hresult is abstract;

      function CreateFromConnectionTokenForUser
      (
         this : access IRemoteSystemConnectionRequestStatics2_Interface;
         user : WinRt.Windows.System.IUser;
         connectionToken : WinRt.HString;
         RetVal : access WinRt.Windows.System.RemoteSystems.IRemoteSystemConnectionRequest
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemConnectionRequestStatics2 : aliased WinRt.IID := (1175392295, 25836, 22926, (168, 0, 79, 46, 229, 141, 239, 25 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemDiscoveryTypeFilter is interface and WinRt.IInspectable;

      function get_RemoteSystemDiscoveryType
      (
         this : access IRemoteSystemDiscoveryTypeFilter_Interface;
         RetVal : access WinRt.Windows.System.RemoteSystems.RemoteSystemDiscoveryType
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemDiscoveryTypeFilter : aliased WinRt.IID := (1121518623, 61018, 17370, (172, 106, 111, 238, 37, 70, 7, 65 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemDiscoveryTypeFilterFactory is interface and WinRt.IInspectable;

      function Create
      (
         this : access IRemoteSystemDiscoveryTypeFilterFactory_Interface;
         discoveryType : WinRt.Windows.System.RemoteSystems.RemoteSystemDiscoveryType;
         RetVal : access WinRt.Windows.System.RemoteSystems.IRemoteSystemDiscoveryTypeFilter
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemDiscoveryTypeFilterFactory : aliased WinRt.IID := (2677979539, 49760, 16737, (146, 242, 156, 2, 31, 35, 254, 93 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemEnumerationCompletedEventArgs is interface and WinRt.IInspectable;

      IID_IRemoteSystemEnumerationCompletedEventArgs : aliased WinRt.IID := (3337108831, 16432, 17236, (160, 96, 20, 241, 178, 44, 84, 93 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemFilter is interface and WinRt.IInspectable;

      IID_IRemoteSystemFilter : aliased WinRt.IID := (1245424100, 39403, 17899, (186, 22, 3, 103, 114, 143, 243, 116 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemKindFilter is interface and WinRt.IInspectable;

      function get_RemoteSystemKinds
      (
         this : access IRemoteSystemKindFilter_Interface;
         RetVal : access GenericObject
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemKindFilter : aliased WinRt.IID := (954321388, 8899, 20214, (144, 26, 187, 177, 199, 170, 212, 237 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemKindFilterFactory is interface and WinRt.IInspectable;

      function Create
      (
         this : access IRemoteSystemKindFilterFactory_Interface;
         remoteSystemKinds : GenericObject;
         RetVal : access WinRt.Windows.System.RemoteSystems.IRemoteSystemKindFilter
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemKindFilterFactory : aliased WinRt.IID := (2717587694, 39402, 16572, (154, 57, 198, 112, 170, 128, 74, 40 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemKindStatics is interface and WinRt.IInspectable;

      function get_Phone
      (
         this : access IRemoteSystemKindStatics_Interface;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      function get_Hub
      (
         this : access IRemoteSystemKindStatics_Interface;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      function get_Holographic
      (
         this : access IRemoteSystemKindStatics_Interface;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      function get_Desktop
      (
         this : access IRemoteSystemKindStatics_Interface;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      function get_Xbox
      (
         this : access IRemoteSystemKindStatics_Interface;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemKindStatics : aliased WinRt.IID := (4130436659, 43796, 16848, (149, 83, 121, 106, 173, 184, 130, 219 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemKindStatics2 is interface and WinRt.IInspectable;

      function get_Iot
      (
         this : access IRemoteSystemKindStatics2_Interface;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      function get_Tablet
      (
         this : access IRemoteSystemKindStatics2_Interface;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      function get_Laptop
      (
         this : access IRemoteSystemKindStatics2_Interface;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemKindStatics2 : aliased WinRt.IID := (3118703568, 1126, 18249, (145, 232, 101, 249, 209, 154, 150, 165 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemRemovedEventArgs is interface and WinRt.IInspectable;

      function get_RemoteSystemId
      (
         this : access IRemoteSystemRemovedEventArgs_Interface;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemRemovedEventArgs : aliased WinRt.IID := (2336036539, 29446, 18922, (183, 223, 103, 213, 113, 76, 176, 19 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemSession is interface and WinRt.IInspectable;

      function get_Id
      (
         this : access IRemoteSystemSession_Interface;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      function get_DisplayName
      (
         this : access IRemoteSystemSession_Interface;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      function get_ControllerDisplayName
      (
         this : access IRemoteSystemSession_Interface;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      function add_Disconnected
      (
         this : access IRemoteSystemSession_Interface;
         handler : GenericObject;
         RetVal : access WinRt.Windows.Foundation.EventRegistrationToken
      )
      return WinRt.Hresult is abstract;

      function remove_Disconnected
      (
         this : access IRemoteSystemSession_Interface;
         token : WinRt.Windows.Foundation.EventRegistrationToken
      )
      return WinRt.Hresult is abstract;

      function CreateParticipantWatcher
      (
         this : access IRemoteSystemSession_Interface;
         RetVal : access WinRt.Windows.System.RemoteSystems.IRemoteSystemSessionParticipantWatcher
      )
      return WinRt.Hresult is abstract;

      function SendInvitationAsync
      (
         this : access IRemoteSystemSession_Interface;
         invitee : WinRt.Windows.System.RemoteSystems.IRemoteSystem;
         RetVal : access GenericObject
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemSession : aliased WinRt.IID := (1766287873, 39642, 18703, (149, 73, 211, 28, 177, 76, 158, 149 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemSessionAddedEventArgs is interface and WinRt.IInspectable;

      function get_SessionInfo
      (
         this : access IRemoteSystemSessionAddedEventArgs_Interface;
         RetVal : access WinRt.Windows.System.RemoteSystems.IRemoteSystemSessionInfo
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemSessionAddedEventArgs : aliased WinRt.IID := (3582318420, 48279, 19513, (153, 180, 190, 202, 118, 224, 76, 63 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemSessionController is interface and WinRt.IInspectable;

      function add_JoinRequested
      (
         this : access IRemoteSystemSessionController_Interface;
         handler : GenericObject;
         RetVal : access WinRt.Windows.Foundation.EventRegistrationToken
      )
      return WinRt.Hresult is abstract;

      function remove_JoinRequested
      (
         this : access IRemoteSystemSessionController_Interface;
         token : WinRt.Windows.Foundation.EventRegistrationToken
      )
      return WinRt.Hresult is abstract;

      function RemoveParticipantAsync
      (
         this : access IRemoteSystemSessionController_Interface;
         pParticipant : WinRt.Windows.System.RemoteSystems.IRemoteSystemSessionParticipant;
         RetVal : access GenericObject
      )
      return WinRt.Hresult is abstract;

      function CreateSessionAsync
      (
         this : access IRemoteSystemSessionController_Interface;
         RetVal : access GenericObject
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemSessionController : aliased WinRt.IID := (3834326482, 26656, 18535, (180, 37, 216, 156, 10, 62, 247, 186 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemSessionControllerFactory is interface and WinRt.IInspectable;

      function CreateController
      (
         this : access IRemoteSystemSessionControllerFactory_Interface;
         displayName : WinRt.HString;
         RetVal : access WinRt.Windows.System.RemoteSystems.IRemoteSystemSessionController
      )
      return WinRt.Hresult is abstract;

      function CreateController
      (
         this : access IRemoteSystemSessionControllerFactory_Interface;
         displayName : WinRt.HString;
         options : WinRt.Windows.System.RemoteSystems.IRemoteSystemSessionOptions;
         RetVal : access WinRt.Windows.System.RemoteSystems.IRemoteSystemSessionController
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemSessionControllerFactory : aliased WinRt.IID := (3217829739, 44093, 16793, (130, 205, 102, 112, 167, 115, 239, 46 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemSessionCreationResult is interface and WinRt.IInspectable;

      function get_Status
      (
         this : access IRemoteSystemSessionCreationResult_Interface;
         RetVal : access WinRt.Windows.System.RemoteSystems.RemoteSystemSessionCreationStatus
      )
      return WinRt.Hresult is abstract;

      function get_Session
      (
         this : access IRemoteSystemSessionCreationResult_Interface;
         RetVal : access WinRt.Windows.System.RemoteSystems.IRemoteSystemSession
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemSessionCreationResult : aliased WinRt.IID := (2811761346, 14302, 17548, (139, 131, 163, 10, 163, 196, 234, 214 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemSessionDisconnectedEventArgs is interface and WinRt.IInspectable;

      function get_Reason
      (
         this : access IRemoteSystemSessionDisconnectedEventArgs_Interface;
         RetVal : access WinRt.Windows.System.RemoteSystems.RemoteSystemSessionDisconnectedReason
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemSessionDisconnectedEventArgs : aliased WinRt.IID := (3725313691, 30661, 17948, (130, 9, 124, 108, 93, 49, 17, 171 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemSessionInfo is interface and WinRt.IInspectable;

      function get_DisplayName
      (
         this : access IRemoteSystemSessionInfo_Interface;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      function get_ControllerDisplayName
      (
         this : access IRemoteSystemSessionInfo_Interface;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      function JoinAsync
      (
         this : access IRemoteSystemSessionInfo_Interface;
         RetVal : access GenericObject
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemSessionInfo : aliased WinRt.IID := (4283299400, 35594, 20122, (153, 5, 105, 228, 184, 65, 197, 136 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemSessionInvitation is interface and WinRt.IInspectable;

      function get_Sender
      (
         this : access IRemoteSystemSessionInvitation_Interface;
         RetVal : access WinRt.Windows.System.RemoteSystems.IRemoteSystem
      )
      return WinRt.Hresult is abstract;

      function get_SessionInfo
      (
         this : access IRemoteSystemSessionInvitation_Interface;
         RetVal : access WinRt.Windows.System.RemoteSystems.IRemoteSystemSessionInfo
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemSessionInvitation : aliased WinRt.IID := (1043516561, 20951, 18278, (161, 33, 37, 81, 108, 59, 130, 148 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemSessionInvitationListener is interface and WinRt.IInspectable;

      function add_InvitationReceived
      (
         this : access IRemoteSystemSessionInvitationListener_Interface;
         handler : GenericObject;
         RetVal : access WinRt.Windows.Foundation.EventRegistrationToken
      )
      return WinRt.Hresult is abstract;

      function remove_InvitationReceived
      (
         this : access IRemoteSystemSessionInvitationListener_Interface;
         token : WinRt.Windows.Foundation.EventRegistrationToken
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemSessionInvitationListener : aliased WinRt.IID := (150208575, 48241, 18913, (135, 74, 49, 221, 255, 154, 39, 185 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemSessionInvitationReceivedEventArgs is interface and WinRt.IInspectable;

      function get_Invitation
      (
         this : access IRemoteSystemSessionInvitationReceivedEventArgs_Interface;
         RetVal : access WinRt.Windows.System.RemoteSystems.IRemoteSystemSessionInvitation
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemSessionInvitationReceivedEventArgs : aliased WinRt.IID := (1586907693, 41229, 20187, (141, 234, 84, 210, 10, 193, 149, 67 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemSessionJoinRequest is interface and WinRt.IInspectable;

      function get_Participant
      (
         this : access IRemoteSystemSessionJoinRequest_Interface;
         RetVal : access WinRt.Windows.System.RemoteSystems.IRemoteSystemSessionParticipant
      )
      return WinRt.Hresult is abstract;

      function Accept_x
      (
         this : access IRemoteSystemSessionJoinRequest_Interface
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemSessionJoinRequest : aliased WinRt.IID := (543162472, 31124, 17201, (134, 209, 216, 157, 136, 37, 133, 238 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemSessionJoinRequestedEventArgs is interface and WinRt.IInspectable;

      function get_JoinRequest
      (
         this : access IRemoteSystemSessionJoinRequestedEventArgs_Interface;
         RetVal : access WinRt.Windows.System.RemoteSystems.IRemoteSystemSessionJoinRequest
      )
      return WinRt.Hresult is abstract;

      function GetDeferral
      (
         this : access IRemoteSystemSessionJoinRequestedEventArgs_Interface;
         RetVal : access WinRt.Windows.Foundation.IDeferral
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemSessionJoinRequestedEventArgs : aliased WinRt.IID := (3687468995, 33465, 18454, (156, 36, 228, 14, 97, 119, 75, 216 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemSessionJoinResult is interface and WinRt.IInspectable;

      function get_Status
      (
         this : access IRemoteSystemSessionJoinResult_Interface;
         RetVal : access WinRt.Windows.System.RemoteSystems.RemoteSystemSessionJoinStatus
      )
      return WinRt.Hresult is abstract;

      function get_Session
      (
         this : access IRemoteSystemSessionJoinResult_Interface;
         RetVal : access WinRt.Windows.System.RemoteSystems.IRemoteSystemSession
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemSessionJoinResult : aliased WinRt.IID := (3464175364, 41022, 16804, (144, 11, 30, 121, 50, 140, 18, 103 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemSessionMessageChannel is interface and WinRt.IInspectable;

      function get_Session
      (
         this : access IRemoteSystemSessionMessageChannel_Interface;
         RetVal : access WinRt.Windows.System.RemoteSystems.IRemoteSystemSession
      )
      return WinRt.Hresult is abstract;

      function BroadcastValueSetAsync
      (
         this : access IRemoteSystemSessionMessageChannel_Interface;
         messageData : WinRt.Windows.Foundation.Collections.IPropertySet;
         RetVal : access GenericObject
      )
      return WinRt.Hresult is abstract;

      function SendValueSetAsync
      (
         this : access IRemoteSystemSessionMessageChannel_Interface;
         messageData : WinRt.Windows.Foundation.Collections.IPropertySet;
         participant : WinRt.Windows.System.RemoteSystems.IRemoteSystemSessionParticipant;
         RetVal : access GenericObject
      )
      return WinRt.Hresult is abstract;

      function SendValueSetToParticipantsAsync
      (
         this : access IRemoteSystemSessionMessageChannel_Interface;
         messageData : WinRt.Windows.Foundation.Collections.IPropertySet;
         participants : GenericObject;
         RetVal : access GenericObject
      )
      return WinRt.Hresult is abstract;

      function add_ValueSetReceived
      (
         this : access IRemoteSystemSessionMessageChannel_Interface;
         handler : GenericObject;
         RetVal : access WinRt.Windows.Foundation.EventRegistrationToken
      )
      return WinRt.Hresult is abstract;

      function remove_ValueSetReceived
      (
         this : access IRemoteSystemSessionMessageChannel_Interface;
         token : WinRt.Windows.Foundation.EventRegistrationToken
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemSessionMessageChannel : aliased WinRt.IID := (2502218026, 29657, 19472, (183, 81, 194, 103, 132, 67, 113, 39 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemSessionMessageChannelFactory is interface and WinRt.IInspectable;

      function Create
      (
         this : access IRemoteSystemSessionMessageChannelFactory_Interface;
         session : WinRt.Windows.System.RemoteSystems.IRemoteSystemSession;
         channelName : WinRt.HString;
         RetVal : access WinRt.Windows.System.RemoteSystems.IRemoteSystemSessionMessageChannel
      )
      return WinRt.Hresult is abstract;

      function Create
      (
         this : access IRemoteSystemSessionMessageChannelFactory_Interface;
         session : WinRt.Windows.System.RemoteSystems.IRemoteSystemSession;
         channelName : WinRt.HString;
         reliability : WinRt.Windows.System.RemoteSystems.RemoteSystemSessionMessageChannelReliability;
         RetVal : access WinRt.Windows.System.RemoteSystems.IRemoteSystemSessionMessageChannel
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemSessionMessageChannelFactory : aliased WinRt.IID := (694033482, 48406, 17048, (183, 206, 65, 84, 130, 176, 225, 29 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemSessionOptions is interface and WinRt.IInspectable;

      function get_IsInviteOnly
      (
         this : access IRemoteSystemSessionOptions_Interface;
         RetVal : access WinRt.Boolean
      )
      return WinRt.Hresult is abstract;

      function put_IsInviteOnly
      (
         this : access IRemoteSystemSessionOptions_Interface;
         value : WinRt.Boolean
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemSessionOptions : aliased WinRt.IID := (1947129685, 33816, 20225, (147, 83, 226, 28, 158, 204, 108, 252 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemSessionParticipant is interface and WinRt.IInspectable;

      function get_RemoteSystem
      (
         this : access IRemoteSystemSessionParticipant_Interface;
         RetVal : access WinRt.Windows.System.RemoteSystems.IRemoteSystem
      )
      return WinRt.Hresult is abstract;

      function GetHostNames
      (
         this : access IRemoteSystemSessionParticipant_Interface;
         RetVal : access GenericObject
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemSessionParticipant : aliased WinRt.IID := (2123367820, 44281, 18217, (138, 23, 68, 231, 186, 237, 93, 204 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemSessionParticipantAddedEventArgs is interface and WinRt.IInspectable;

      function get_Participant
      (
         this : access IRemoteSystemSessionParticipantAddedEventArgs_Interface;
         RetVal : access WinRt.Windows.System.RemoteSystems.IRemoteSystemSessionParticipant
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemSessionParticipantAddedEventArgs : aliased WinRt.IID := (3545913304, 51617, 19383, (182, 176, 121, 187, 145, 173, 249, 61 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemSessionParticipantRemovedEventArgs is interface and WinRt.IInspectable;

      function get_Participant
      (
         this : access IRemoteSystemSessionParticipantRemovedEventArgs_Interface;
         RetVal : access WinRt.Windows.System.RemoteSystems.IRemoteSystemSessionParticipant
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemSessionParticipantRemovedEventArgs : aliased WinRt.IID := (2255417480, 56936, 19135, (136, 161, 249, 13, 22, 39, 65, 146 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemSessionParticipantWatcher is interface and WinRt.IInspectable;

      function Start
      (
         this : access IRemoteSystemSessionParticipantWatcher_Interface
      )
      return WinRt.Hresult is abstract;

      function Stop
      (
         this : access IRemoteSystemSessionParticipantWatcher_Interface
      )
      return WinRt.Hresult is abstract;

      function get_Status
      (
         this : access IRemoteSystemSessionParticipantWatcher_Interface;
         RetVal : access WinRt.Windows.System.RemoteSystems.RemoteSystemSessionParticipantWatcherStatus
      )
      return WinRt.Hresult is abstract;

      function add_Added
      (
         this : access IRemoteSystemSessionParticipantWatcher_Interface;
         handler : GenericObject;
         RetVal : access WinRt.Windows.Foundation.EventRegistrationToken
      )
      return WinRt.Hresult is abstract;

      function remove_Added
      (
         this : access IRemoteSystemSessionParticipantWatcher_Interface;
         token : WinRt.Windows.Foundation.EventRegistrationToken
      )
      return WinRt.Hresult is abstract;

      function add_Removed
      (
         this : access IRemoteSystemSessionParticipantWatcher_Interface;
         handler : GenericObject;
         RetVal : access WinRt.Windows.Foundation.EventRegistrationToken
      )
      return WinRt.Hresult is abstract;

      function remove_Removed
      (
         this : access IRemoteSystemSessionParticipantWatcher_Interface;
         token : WinRt.Windows.Foundation.EventRegistrationToken
      )
      return WinRt.Hresult is abstract;

      function add_EnumerationCompleted
      (
         this : access IRemoteSystemSessionParticipantWatcher_Interface;
         handler : GenericObject;
         RetVal : access WinRt.Windows.Foundation.EventRegistrationToken
      )
      return WinRt.Hresult is abstract;

      function remove_EnumerationCompleted
      (
         this : access IRemoteSystemSessionParticipantWatcher_Interface;
         token : WinRt.Windows.Foundation.EventRegistrationToken
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemSessionParticipantWatcher : aliased WinRt.IID := (3705471692, 43655, 19833, (182, 204, 68, 89, 179, 233, 32, 117 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemSessionRemovedEventArgs is interface and WinRt.IInspectable;

      function get_SessionInfo
      (
         this : access IRemoteSystemSessionRemovedEventArgs_Interface;
         RetVal : access WinRt.Windows.System.RemoteSystems.IRemoteSystemSessionInfo
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemSessionRemovedEventArgs : aliased WinRt.IID := (2944569678, 14753, 19946, (157, 99, 67, 121, 141, 91, 187, 208 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemSessionStatics is interface and WinRt.IInspectable;

      function CreateWatcher
      (
         this : access IRemoteSystemSessionStatics_Interface;
         RetVal : access WinRt.Windows.System.RemoteSystems.IRemoteSystemSessionWatcher
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemSessionStatics : aliased WinRt.IID := (2233764255, 64800, 17635, (149, 101, 231, 90, 59, 20, 198, 110 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemSessionUpdatedEventArgs is interface and WinRt.IInspectable;

      function get_SessionInfo
      (
         this : access IRemoteSystemSessionUpdatedEventArgs_Interface;
         RetVal : access WinRt.Windows.System.RemoteSystems.IRemoteSystemSessionInfo
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemSessionUpdatedEventArgs : aliased WinRt.IID := (377966697, 8990, 19601, (142, 200, 179, 163, 157, 158, 85, 163 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemSessionValueSetReceivedEventArgs is interface and WinRt.IInspectable;

      function get_Sender
      (
         this : access IRemoteSystemSessionValueSetReceivedEventArgs_Interface;
         RetVal : access WinRt.Windows.System.RemoteSystems.IRemoteSystemSessionParticipant
      )
      return WinRt.Hresult is abstract;

      function get_Message
      (
         this : access IRemoteSystemSessionValueSetReceivedEventArgs_Interface;
         RetVal : access WinRt.Windows.Foundation.Collections.IPropertySet
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemSessionValueSetReceivedEventArgs : aliased WinRt.IID := (116594565, 11685, 20056, (167, 143, 158, 141, 7, 132, 238, 37 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemSessionWatcher is interface and WinRt.IInspectable;

      function Start
      (
         this : access IRemoteSystemSessionWatcher_Interface
      )
      return WinRt.Hresult is abstract;

      function Stop
      (
         this : access IRemoteSystemSessionWatcher_Interface
      )
      return WinRt.Hresult is abstract;

      function get_Status
      (
         this : access IRemoteSystemSessionWatcher_Interface;
         RetVal : access WinRt.Windows.System.RemoteSystems.RemoteSystemSessionWatcherStatus
      )
      return WinRt.Hresult is abstract;

      function add_Added
      (
         this : access IRemoteSystemSessionWatcher_Interface;
         handler : GenericObject;
         RetVal : access WinRt.Windows.Foundation.EventRegistrationToken
      )
      return WinRt.Hresult is abstract;

      function remove_Added
      (
         this : access IRemoteSystemSessionWatcher_Interface;
         token : WinRt.Windows.Foundation.EventRegistrationToken
      )
      return WinRt.Hresult is abstract;

      function add_Updated
      (
         this : access IRemoteSystemSessionWatcher_Interface;
         handler : GenericObject;
         RetVal : access WinRt.Windows.Foundation.EventRegistrationToken
      )
      return WinRt.Hresult is abstract;

      function remove_Updated
      (
         this : access IRemoteSystemSessionWatcher_Interface;
         token : WinRt.Windows.Foundation.EventRegistrationToken
      )
      return WinRt.Hresult is abstract;

      function add_Removed
      (
         this : access IRemoteSystemSessionWatcher_Interface;
         handler : GenericObject;
         RetVal : access WinRt.Windows.Foundation.EventRegistrationToken
      )
      return WinRt.Hresult is abstract;

      function remove_Removed
      (
         this : access IRemoteSystemSessionWatcher_Interface;
         token : WinRt.Windows.Foundation.EventRegistrationToken
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemSessionWatcher : aliased WinRt.IID := (2147738432, 3137, 19042, (182, 215, 189, 190, 43, 25, 190, 45 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemStatics is interface and WinRt.IInspectable;

      function FindByHostNameAsync
      (
         this : access IRemoteSystemStatics_Interface;
         hostName : WinRt.Windows.Networking.IHostName;
         RetVal : access GenericObject
      )
      return WinRt.Hresult is abstract;

      function CreateWatcher
      (
         this : access IRemoteSystemStatics_Interface;
         RetVal : access WinRt.Windows.System.RemoteSystems.IRemoteSystemWatcher
      )
      return WinRt.Hresult is abstract;

      function CreateWatcher
      (
         this : access IRemoteSystemStatics_Interface;
         filters : GenericObject;
         RetVal : access WinRt.Windows.System.RemoteSystems.IRemoteSystemWatcher
      )
      return WinRt.Hresult is abstract;

      function RequestAccessAsync
      (
         this : access IRemoteSystemStatics_Interface;
         RetVal : access GenericObject
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemStatics : aliased WinRt.IID := (2760225682, 65323, 19271, (190, 98, 116, 63, 47, 20, 15, 48 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemStatics2 is interface and WinRt.IInspectable;

      function IsAuthorizationKindEnabled
      (
         this : access IRemoteSystemStatics2_Interface;
         kind : WinRt.Windows.System.RemoteSystems.RemoteSystemAuthorizationKind;
         RetVal : access WinRt.Boolean
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemStatics2 : aliased WinRt.IID := (211348938, 28569, 19538, (162, 114, 234, 79, 54, 71, 23, 68 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemStatics3 is interface and WinRt.IInspectable;

      function CreateWatcherForUser
      (
         this : access IRemoteSystemStatics3_Interface;
         user : WinRt.Windows.System.IUser;
         RetVal : access WinRt.Windows.System.RemoteSystems.IRemoteSystemWatcher
      )
      return WinRt.Hresult is abstract;

      function CreateWatcherForUser
      (
         this : access IRemoteSystemStatics3_Interface;
         user : WinRt.Windows.System.IUser;
         filters : GenericObject;
         RetVal : access WinRt.Windows.System.RemoteSystems.IRemoteSystemWatcher
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemStatics3 : aliased WinRt.IID := (2576740719, 2876, 23237, (179, 37, 204, 115, 244, 55, 223, 205 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemStatusTypeFilter is interface and WinRt.IInspectable;

      function get_RemoteSystemStatusType
      (
         this : access IRemoteSystemStatusTypeFilter_Interface;
         RetVal : access WinRt.Windows.System.RemoteSystems.RemoteSystemStatusType
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemStatusTypeFilter : aliased WinRt.IID := (205082958, 52150, 18295, (133, 52, 46, 12, 82, 26, 255, 162 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemStatusTypeFilterFactory is interface and WinRt.IInspectable;

      function Create
      (
         this : access IRemoteSystemStatusTypeFilterFactory_Interface;
         remoteSystemStatusType : WinRt.Windows.System.RemoteSystems.RemoteSystemStatusType;
         RetVal : access WinRt.Windows.System.RemoteSystems.IRemoteSystemStatusTypeFilter
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemStatusTypeFilterFactory : aliased WinRt.IID := (869234938, 55076, 16677, (172, 122, 141, 40, 30, 68, 201, 73 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemUpdatedEventArgs is interface and WinRt.IInspectable;

      function get_RemoteSystem
      (
         this : access IRemoteSystemUpdatedEventArgs_Interface;
         RetVal : access WinRt.Windows.System.RemoteSystems.IRemoteSystem
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemUpdatedEventArgs : aliased WinRt.IID := (1963130638, 56267, 16725, (180, 202, 179, 10, 4, 242, 118, 39 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemWatcher is interface and WinRt.IInspectable;

      function Start
      (
         this : access IRemoteSystemWatcher_Interface
      )
      return WinRt.Hresult is abstract;

      function Stop
      (
         this : access IRemoteSystemWatcher_Interface
      )
      return WinRt.Hresult is abstract;

      function add_RemoteSystemAdded
      (
         this : access IRemoteSystemWatcher_Interface;
         handler : GenericObject;
         RetVal : access WinRt.Windows.Foundation.EventRegistrationToken
      )
      return WinRt.Hresult is abstract;

      function remove_RemoteSystemAdded
      (
         this : access IRemoteSystemWatcher_Interface;
         token : WinRt.Windows.Foundation.EventRegistrationToken
      )
      return WinRt.Hresult is abstract;

      function add_RemoteSystemUpdated
      (
         this : access IRemoteSystemWatcher_Interface;
         handler : GenericObject;
         RetVal : access WinRt.Windows.Foundation.EventRegistrationToken
      )
      return WinRt.Hresult is abstract;

      function remove_RemoteSystemUpdated
      (
         this : access IRemoteSystemWatcher_Interface;
         token : WinRt.Windows.Foundation.EventRegistrationToken
      )
      return WinRt.Hresult is abstract;

      function add_RemoteSystemRemoved
      (
         this : access IRemoteSystemWatcher_Interface;
         handler : GenericObject;
         RetVal : access WinRt.Windows.Foundation.EventRegistrationToken
      )
      return WinRt.Hresult is abstract;

      function remove_RemoteSystemRemoved
      (
         this : access IRemoteSystemWatcher_Interface;
         token : WinRt.Windows.Foundation.EventRegistrationToken
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemWatcher : aliased WinRt.IID := (1566575742, 11271, 18629, (136, 156, 69, 93, 43, 9, 151, 113 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemWatcher2 is interface and WinRt.IInspectable;

      function add_EnumerationCompleted
      (
         this : access IRemoteSystemWatcher2_Interface;
         handler : GenericObject;
         RetVal : access WinRt.Windows.Foundation.EventRegistrationToken
      )
      return WinRt.Hresult is abstract;

      function remove_EnumerationCompleted
      (
         this : access IRemoteSystemWatcher2_Interface;
         token : WinRt.Windows.Foundation.EventRegistrationToken
      )
      return WinRt.Hresult is abstract;

      function add_ErrorOccurred
      (
         this : access IRemoteSystemWatcher2_Interface;
         handler : GenericObject;
         RetVal : access WinRt.Windows.Foundation.EventRegistrationToken
      )
      return WinRt.Hresult is abstract;

      function remove_ErrorOccurred
      (
         this : access IRemoteSystemWatcher2_Interface;
         token : WinRt.Windows.Foundation.EventRegistrationToken
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemWatcher2 : aliased WinRt.IID := (1933797120, 6602, 18681, (164, 205, 120, 15, 122, 213, 140, 113 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemWatcher3 is interface and WinRt.IInspectable;

      function get_User
      (
         this : access IRemoteSystemWatcher3_Interface;
         RetVal : access WinRt.Windows.System.IUser
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemWatcher3 : aliased WinRt.IID := (4154200015, 43283, 21971, (132, 19, 65, 143, 207, 21, 186, 84 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemWatcherErrorOccurredEventArgs is interface and WinRt.IInspectable;

      function get_Error
      (
         this : access IRemoteSystemWatcherErrorOccurredEventArgs_Interface;
         RetVal : access WinRt.Windows.System.RemoteSystems.RemoteSystemWatcherError
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemWatcherErrorOccurredEventArgs : aliased WinRt.IID := (1959118511, 20756, 17446, (146, 22, 32, 216, 31, 133, 25, 174 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemWebAccountFilter is interface and WinRt.IInspectable;

      function get_Account
      (
         this : access IRemoteSystemWebAccountFilter_Interface;
         RetVal : access WinRt.Windows.Security.Credentials.IWebAccount
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemWebAccountFilter : aliased WinRt.IID := (1068980339, 34760, 23951, (151, 126, 246, 159, 150, 214, 114, 56 ));

   -----------------------------------------------------------------------------
   -- type IRemoteSystemWebAccountFilterFactory is interface and WinRt.IInspectable;

      function Create
      (
         this : access IRemoteSystemWebAccountFilterFactory_Interface;
         account : WinRt.Windows.Security.Credentials.IWebAccount;
         RetVal : access WinRt.Windows.System.RemoteSystems.IRemoteSystemWebAccountFilter
      )
      return WinRt.Hresult is abstract;

      IID_IRemoteSystemWebAccountFilterFactory : aliased WinRt.IID := (881469193, 24397, 20775, (180, 167, 191, 153, 213, 37, 43, 27 ));

end WinRt.Windows.System.RemoteSystems;
