--------------------------------------------------------------------------------
-- <auto-generated>                                                           --
--     This code was generated by a tool.                                     --
--                                                                            --
--     Changes to this file may cause incorrect behavior and will be lost if  --
--     the code is regenerated.                                               --
-- </auto-generated>                                                          --
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--                                                                            --
--    Copyright(c) 2023 Alexander Gamper, All Rights Reserved.                --
--                                                                            --
--    Ada-WinRT                                                               --
--    Version   : 3.0.0.0                                                     --
--                                                                            --
-- This program is free software: you can redistribute it and / or modify     --
-- it under the terms of the GNU Lesser General Public License as published by--
-- the Free Software Foundation, either version 3 of the License, or          --
-- (at your option) any later version.                                        --
--                                                                            --
-- This program is distributed in the hope that it will be useful,            --
-- but WITHOUT ANY WARRANTY; without even the implied warranty of             --
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the               --
-- GNU Lesser General Public License for more details.                        --
--                                                                            --
-- You should have received a copy of the GNU Lesser General Public License   --
-- along with this program.If not, see http://www.gnu.org/licenses            --
--                                                                            --
--------------------------------------------------------------------------------
with WinRt.Windows.Foundation;
limited with WinRt.Windows.Storage;
with Ada.Finalization;
--------------------------------------------------------------------------------
package WinRt.Windows.Media.AppRecording is

   pragma PreElaborate;

   -----------------------------------------------------------------------------
   -- Forward Interface declarations
   -----------------------------------------------------------------------------

   type IAppRecordingManager_Interface is interface and WinRt.IInspectable_Interface;
   type IAppRecordingManager is access all IAppRecordingManager_Interface'Class;
   type IAppRecordingManager_Ptr is access all IAppRecordingManager;

   type IAppRecordingManagerStatics_Interface is interface and WinRt.IInspectable_Interface;
   type IAppRecordingManagerStatics is access all IAppRecordingManagerStatics_Interface'Class;
   type IAppRecordingManagerStatics_Ptr is access all IAppRecordingManagerStatics;

   type IAppRecordingResult_Interface is interface and WinRt.IInspectable_Interface;
   type IAppRecordingResult is access all IAppRecordingResult_Interface'Class;
   type IAppRecordingResult_Ptr is access all IAppRecordingResult;

   type IAppRecordingSaveScreenshotResult_Interface is interface and WinRt.IInspectable_Interface;
   type IAppRecordingSaveScreenshotResult is access all IAppRecordingSaveScreenshotResult_Interface'Class;
   type IAppRecordingSaveScreenshotResult_Ptr is access all IAppRecordingSaveScreenshotResult;

   type IAppRecordingSavedScreenshotInfo_Interface is interface and WinRt.IInspectable_Interface;
   type IAppRecordingSavedScreenshotInfo is access all IAppRecordingSavedScreenshotInfo_Interface'Class;
   type IAppRecordingSavedScreenshotInfo_Ptr is access all IAppRecordingSavedScreenshotInfo;

   type IAppRecordingStatus_Interface is interface and WinRt.IInspectable_Interface;
   type IAppRecordingStatus is access all IAppRecordingStatus_Interface'Class;
   type IAppRecordingStatus_Ptr is access all IAppRecordingStatus;

   type IAppRecordingStatusDetails_Interface is interface and WinRt.IInspectable_Interface;
   type IAppRecordingStatusDetails is access all IAppRecordingStatusDetails_Interface'Class;
   type IAppRecordingStatusDetails_Ptr is access all IAppRecordingStatusDetails;

   -----------------------------------------------------------------------------
   -- Enum declarations
   -----------------------------------------------------------------------------

   type AppRecordingSaveScreenshotOption is (
      None_e,
      HdrContentVisible_e
   );
   for AppRecordingSaveScreenshotOption use (
      None_e => 0,
      HdrContentVisible_e => 1
   );
   type AppRecordingSaveScreenshotOption_Ptr is access all AppRecordingSaveScreenshotOption;

   -----------------------------------------------------------------------------
   -- Record declarations
   -----------------------------------------------------------------------------

   type AppRecordingContract is record
      null;
   end record with Convention => C_Pass_By_Copy;
   type AppRecordingContract_Ptr is access all AppRecordingContract;

   -----------------------------------------------------------------------------
   -- Interface declarations
   -----------------------------------------------------------------------------

   -----------------------------------------------------------------------------
   -- type IAppRecordingManager is interface and WinRt.IInspectable;

      function GetStatus
      (
         this : access IAppRecordingManager_Interface;
         RetVal : access WinRt.Windows.Media.AppRecording.IAppRecordingStatus
      )
      return WinRt.Hresult is abstract;

      function StartRecordingToFileAsync
      (
         this : access IAppRecordingManager_Interface;
         file : WinRt.Windows.Storage.IStorageFile;
         RetVal : access GenericObject
      )
      return WinRt.Hresult is abstract;

      function RecordTimeSpanToFileAsync
      (
         this : access IAppRecordingManager_Interface;
         startTime : WinRt.Windows.Foundation.DateTime;
         duration : WinRt.Windows.Foundation.TimeSpan;
         file : WinRt.Windows.Storage.IStorageFile;
         RetVal : access GenericObject
      )
      return WinRt.Hresult is abstract;

      function get_SupportedScreenshotMediaEncodingSubtypes
      (
         this : access IAppRecordingManager_Interface;
         RetVal : access GenericObject
      )
      return WinRt.Hresult is abstract;

      function SaveScreenshotToFilesAsync
      (
         this : access IAppRecordingManager_Interface;
         folder : WinRt.Windows.Storage.IStorageFolder;
         filenamePrefix : WinRt.HString;
         option : WinRt.Windows.Media.AppRecording.AppRecordingSaveScreenshotOption;
         requestedFormats : GenericObject;
         RetVal : access GenericObject
      )
      return WinRt.Hresult is abstract;

      IID_IAppRecordingManager : aliased WinRt.IID := (3890372726, 41028, 18658, (165, 18, 48, 148, 213, 116, 199, 204 ));

   -----------------------------------------------------------------------------
   -- type IAppRecordingManagerStatics is interface and WinRt.IInspectable;

      function GetDefault
      (
         this : access IAppRecordingManagerStatics_Interface;
         RetVal : access WinRt.Windows.Media.AppRecording.IAppRecordingManager
      )
      return WinRt.Hresult is abstract;

      IID_IAppRecordingManagerStatics : aliased WinRt.IID := (1357318647, 14542, 19411, (157, 178, 231, 43, 190, 157, 225, 29 ));

   -----------------------------------------------------------------------------
   -- type IAppRecordingResult is interface and WinRt.IInspectable;

      function get_Succeeded
      (
         this : access IAppRecordingResult_Interface;
         RetVal : access WinRt.Boolean
      )
      return WinRt.Hresult is abstract;

      function get_ExtendedError
      (
         this : access IAppRecordingResult_Interface;
         RetVal : access WinRt.Windows.Foundation.HResult
      )
      return WinRt.Hresult is abstract;

      function get_Duration
      (
         this : access IAppRecordingResult_Interface;
         RetVal : access WinRt.Windows.Foundation.TimeSpan
      )
      return WinRt.Hresult is abstract;

      function get_IsFileTruncated
      (
         this : access IAppRecordingResult_Interface;
         RetVal : access WinRt.Boolean
      )
      return WinRt.Hresult is abstract;

      IID_IAppRecordingResult : aliased WinRt.IID := (982517860, 50797, 18169, (178, 217, 91, 194, 218, 208, 112, 215 ));

   -----------------------------------------------------------------------------
   -- type IAppRecordingSaveScreenshotResult is interface and WinRt.IInspectable;

      function get_Succeeded
      (
         this : access IAppRecordingSaveScreenshotResult_Interface;
         RetVal : access WinRt.Boolean
      )
      return WinRt.Hresult is abstract;

      function get_ExtendedError
      (
         this : access IAppRecordingSaveScreenshotResult_Interface;
         RetVal : access WinRt.Windows.Foundation.HResult
      )
      return WinRt.Hresult is abstract;

      function get_SavedScreenshotInfos
      (
         this : access IAppRecordingSaveScreenshotResult_Interface;
         RetVal : access GenericObject
      )
      return WinRt.Hresult is abstract;

      IID_IAppRecordingSaveScreenshotResult : aliased WinRt.IID := (2623245578, 2747, 17495, (170, 238, 36, 249, 193, 46, 199, 120 ));

   -----------------------------------------------------------------------------
   -- type IAppRecordingSavedScreenshotInfo is interface and WinRt.IInspectable;

      function get_File
      (
         this : access IAppRecordingSavedScreenshotInfo_Interface;
         RetVal : access WinRt.Windows.Storage.IStorageFile
      )
      return WinRt.Hresult is abstract;

      function get_MediaEncodingSubtype
      (
         this : access IAppRecordingSavedScreenshotInfo_Interface;
         RetVal : access WinRt.HString
      )
      return WinRt.Hresult is abstract;

      IID_IAppRecordingSavedScreenshotInfo : aliased WinRt.IID := (2607033610, 6298, 19712, (191, 37, 225, 187, 18, 73, 213, 148 ));

   -----------------------------------------------------------------------------
   -- type IAppRecordingStatus is interface and WinRt.IInspectable;

      function get_CanRecord
      (
         this : access IAppRecordingStatus_Interface;
         RetVal : access WinRt.Boolean
      )
      return WinRt.Hresult is abstract;

      function get_CanRecordTimeSpan
      (
         this : access IAppRecordingStatus_Interface;
         RetVal : access WinRt.Boolean
      )
      return WinRt.Hresult is abstract;

      function get_HistoricalBufferDuration
      (
         this : access IAppRecordingStatus_Interface;
         RetVal : access WinRt.Windows.Foundation.TimeSpan
      )
      return WinRt.Hresult is abstract;

      function get_Details
      (
         this : access IAppRecordingStatus_Interface;
         RetVal : access WinRt.Windows.Media.AppRecording.IAppRecordingStatusDetails
      )
      return WinRt.Hresult is abstract;

      IID_IAppRecordingStatus : aliased WinRt.IID := (487376940, 48152, 19338, (166, 239, 18, 126, 250, 179, 181, 217 ));

   -----------------------------------------------------------------------------
   -- type IAppRecordingStatusDetails is interface and WinRt.IInspectable;

      function get_IsAnyAppBroadcasting
      (
         this : access IAppRecordingStatusDetails_Interface;
         RetVal : access WinRt.Boolean
      )
      return WinRt.Hresult is abstract;

      function get_IsCaptureResourceUnavailable
      (
         this : access IAppRecordingStatusDetails_Interface;
         RetVal : access WinRt.Boolean
      )
      return WinRt.Hresult is abstract;

      function get_IsGameStreamInProgress
      (
         this : access IAppRecordingStatusDetails_Interface;
         RetVal : access WinRt.Boolean
      )
      return WinRt.Hresult is abstract;

      function get_IsTimeSpanRecordingDisabled
      (
         this : access IAppRecordingStatusDetails_Interface;
         RetVal : access WinRt.Boolean
      )
      return WinRt.Hresult is abstract;

      function get_IsGpuConstrained
      (
         this : access IAppRecordingStatusDetails_Interface;
         RetVal : access WinRt.Boolean
      )
      return WinRt.Hresult is abstract;

      function get_IsAppInactive
      (
         this : access IAppRecordingStatusDetails_Interface;
         RetVal : access WinRt.Boolean
      )
      return WinRt.Hresult is abstract;

      function get_IsBlockedForApp
      (
         this : access IAppRecordingStatusDetails_Interface;
         RetVal : access WinRt.Boolean
      )
      return WinRt.Hresult is abstract;

      function get_IsDisabledByUser
      (
         this : access IAppRecordingStatusDetails_Interface;
         RetVal : access WinRt.Boolean
      )
      return WinRt.Hresult is abstract;

      function get_IsDisabledBySystem
      (
         this : access IAppRecordingStatusDetails_Interface;
         RetVal : access WinRt.Boolean
      )
      return WinRt.Hresult is abstract;

      IID_IAppRecordingStatusDetails : aliased WinRt.IID := (3040389552, 5357, 17426, (172, 69, 109, 103, 44, 156, 153, 73 ));

end WinRt.Windows.Media.AppRecording;
