--------------------------------------------------------------------------------
-- <auto-generated>                                                           --
--     This code was generated by a tool.                                     --
--                                                                            --
--     Changes to this file may cause incorrect behavior and will be lost if  --
--     the code is regenerated.                                               --
-- </auto-generated>                                                          --
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--                                                                            --
--    Copyright(c) 2023 Alexander Gamper, All Rights Reserved.                --
--                                                                            --
--    Ada-WinRT                                                               --
--    Version   : 3.0.0.0                                                     --
--                                                                            --
-- This program is free software: you can redistribute it and / or modify     --
-- it under the terms of the GNU Lesser General Public License as published by--
-- the Free Software Foundation, either version 3 of the License, or          --
-- (at your option) any later version.                                        --
--                                                                            --
-- This program is distributed in the hope that it will be useful,            --
-- but WITHOUT ANY WARRANTY; without even the implied warranty of             --
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the               --
-- GNU Lesser General Public License for more details.                        --
--                                                                            --
-- You should have received a copy of the GNU Lesser General Public License   --
-- along with this program.If not, see http://www.gnu.org/licenses            --
--                                                                            --
--------------------------------------------------------------------------------
with WinRt.Windows.Foundation; use WinRt.Windows.Foundation;
with Ada.Unchecked_Deallocation;
--------------------------------------------------------------------------------
package body WinRt.Windows.UI.WindowManagement.Preview is

   -----------------------------------------------------------------------------
   -- RuntimeClass Initialization/Finalization for WindowManagementPreview

   procedure Initialize (this : in out WindowManagementPreview) is
   begin
      null;
   end;

   procedure Finalize (this : in out WindowManagementPreview) is
      temp : WinRt.UInt32 := 0;
      procedure Free is new Ada.Unchecked_Deallocation (IWindowManagementPreview, IWindowManagementPreview_Ptr);
   begin
      if this.m_IWindowManagementPreview /= null then
         if this.m_IWindowManagementPreview.all /= null then
            temp := this.m_IWindowManagementPreview.all.Release;
            Free (this.m_IWindowManagementPreview);
         end if;
      end if;
   end;

   -----------------------------------------------------------------------------
   -- Static Interfaces for WindowManagementPreview

   procedure SetPreferredMinSize
   (
      window : Windows.UI.WindowManagement.AppWindow'Class;
      preferredFrameMinSize : Windows.Foundation.Size
   ) is
      Hr               : WinRt.HResult := S_OK;
      tmp              : WinRt.HResult := S_OK;
      m_hString        : constant WinRt.HString := To_HString ("Windows.UI.WindowManagement.Preview.WindowManagementPreview");
      m_Factory        : access WinRt.Windows.UI.WindowManagement.Preview.IWindowManagementPreviewStatics_Interface'Class := null;
      temp             : WinRt.UInt32 := 0;
   begin
      Hr := RoGetActivationFactory (m_hString, IID_IWindowManagementPreviewStatics'Access , m_Factory'Address);
      if Hr = S_OK then
         Hr := m_Factory.SetPreferredMinSize (window.m_IAppWindow.all, preferredFrameMinSize);
         temp := m_Factory.Release;
         if Hr /= S_OK then
            raise Program_Error;
         end if;
      end if;
      tmp := WindowsDeleteString (m_hString);
   end;

   -----------------------------------------------------------------------------
   -- Implemented Interfaces for WindowManagementPreview

end WinRt.Windows.UI.WindowManagement.Preview;
